// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: grpc.proto

package builder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	API_SendRemote_FullMethodName             = "/builder.API/SendRemote"
	API_SendClientStreamRemote_FullMethodName = "/builder.API/SendClientStreamRemote"
	API_SendServerStreamRemote_FullMethodName = "/builder.API/SendServerStreamRemote"
	API_SendStreamRemote_FullMethodName       = "/builder.API/SendStreamRemote"
	API_SendLocal_FullMethodName              = "/builder.API/SendLocal"
	API_SendClientStreamLocal_FullMethodName  = "/builder.API/SendClientStreamLocal"
	API_SendServerStreamLocal_FullMethodName  = "/builder.API/SendServerStreamLocal"
	API_SendStreamLocal_FullMethodName        = "/builder.API/SendStreamLocal"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	SendRemote(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
	SendClientStreamRemote(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamRemoteClient, error)
	SendServerStreamRemote(ctx context.Context, in *Message, opts ...grpc.CallOption) (API_SendServerStreamRemoteClient, error)
	SendStreamRemote(ctx context.Context, opts ...grpc.CallOption) (API_SendStreamRemoteClient, error)
	SendLocal(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
	SendClientStreamLocal(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamLocalClient, error)
	SendServerStreamLocal(ctx context.Context, in *Message, opts ...grpc.CallOption) (API_SendServerStreamLocalClient, error)
	SendStreamLocal(ctx context.Context, opts ...grpc.CallOption) (API_SendStreamLocalClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) SendRemote(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, API_SendRemote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SendClientStreamRemote(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamRemoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], API_SendClientStreamRemote_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendClientStreamRemoteClient{stream}
	return x, nil
}

type API_SendClientStreamRemoteClient interface {
	Send(*Message) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type aPISendClientStreamRemoteClient struct {
	grpc.ClientStream
}

func (x *aPISendClientStreamRemoteClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendClientStreamRemoteClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendServerStreamRemote(ctx context.Context, in *Message, opts ...grpc.CallOption) (API_SendServerStreamRemoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[1], API_SendServerStreamRemote_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendServerStreamRemoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SendServerStreamRemoteClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPISendServerStreamRemoteClient struct {
	grpc.ClientStream
}

func (x *aPISendServerStreamRemoteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendStreamRemote(ctx context.Context, opts ...grpc.CallOption) (API_SendStreamRemoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[2], API_SendStreamRemote_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendStreamRemoteClient{stream}
	return x, nil
}

type API_SendStreamRemoteClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPISendStreamRemoteClient struct {
	grpc.ClientStream
}

func (x *aPISendStreamRemoteClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendStreamRemoteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendLocal(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, API_SendLocal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SendClientStreamLocal(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamLocalClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[3], API_SendClientStreamLocal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendClientStreamLocalClient{stream}
	return x, nil
}

type API_SendClientStreamLocalClient interface {
	Send(*Message) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type aPISendClientStreamLocalClient struct {
	grpc.ClientStream
}

func (x *aPISendClientStreamLocalClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendClientStreamLocalClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendServerStreamLocal(ctx context.Context, in *Message, opts ...grpc.CallOption) (API_SendServerStreamLocalClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[4], API_SendServerStreamLocal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendServerStreamLocalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SendServerStreamLocalClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPISendServerStreamLocalClient struct {
	grpc.ClientStream
}

func (x *aPISendServerStreamLocalClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendStreamLocal(ctx context.Context, opts ...grpc.CallOption) (API_SendStreamLocalClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[5], API_SendStreamLocal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendStreamLocalClient{stream}
	return x, nil
}

type API_SendStreamLocalClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPISendStreamLocalClient struct {
	grpc.ClientStream
}

func (x *aPISendStreamLocalClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendStreamLocalClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	SendRemote(context.Context, *Message) (*Response, error)
	SendClientStreamRemote(API_SendClientStreamRemoteServer) error
	SendServerStreamRemote(*Message, API_SendServerStreamRemoteServer) error
	SendStreamRemote(API_SendStreamRemoteServer) error
	SendLocal(context.Context, *Message) (*Response, error)
	SendClientStreamLocal(API_SendClientStreamLocalServer) error
	SendServerStreamLocal(*Message, API_SendServerStreamLocalServer) error
	SendStreamLocal(API_SendStreamLocalServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) SendRemote(context.Context, *Message) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRemote not implemented")
}
func (UnimplementedAPIServer) SendClientStreamRemote(API_SendClientStreamRemoteServer) error {
	return status.Errorf(codes.Unimplemented, "method SendClientStreamRemote not implemented")
}
func (UnimplementedAPIServer) SendServerStreamRemote(*Message, API_SendServerStreamRemoteServer) error {
	return status.Errorf(codes.Unimplemented, "method SendServerStreamRemote not implemented")
}
func (UnimplementedAPIServer) SendStreamRemote(API_SendStreamRemoteServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStreamRemote not implemented")
}
func (UnimplementedAPIServer) SendLocal(context.Context, *Message) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLocal not implemented")
}
func (UnimplementedAPIServer) SendClientStreamLocal(API_SendClientStreamLocalServer) error {
	return status.Errorf(codes.Unimplemented, "method SendClientStreamLocal not implemented")
}
func (UnimplementedAPIServer) SendServerStreamLocal(*Message, API_SendServerStreamLocalServer) error {
	return status.Errorf(codes.Unimplemented, "method SendServerStreamLocal not implemented")
}
func (UnimplementedAPIServer) SendStreamLocal(API_SendStreamLocalServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStreamLocal not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_SendRemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SendRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_SendRemote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SendRemote(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SendClientStreamRemote_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendClientStreamRemote(&aPISendClientStreamRemoteServer{stream})
}

type API_SendClientStreamRemoteServer interface {
	SendAndClose(*Response) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type aPISendClientStreamRemoteServer struct {
	grpc.ServerStream
}

func (x *aPISendClientStreamRemoteServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendClientStreamRemoteServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendServerStreamRemote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Message)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SendServerStreamRemote(m, &aPISendServerStreamRemoteServer{stream})
}

type API_SendServerStreamRemoteServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type aPISendServerStreamRemoteServer struct {
	grpc.ServerStream
}

func (x *aPISendServerStreamRemoteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SendStreamRemote_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendStreamRemote(&aPISendStreamRemoteServer{stream})
}

type API_SendStreamRemoteServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type aPISendStreamRemoteServer struct {
	grpc.ServerStream
}

func (x *aPISendStreamRemoteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendStreamRemoteServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SendLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_SendLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SendLocal(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SendClientStreamLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendClientStreamLocal(&aPISendClientStreamLocalServer{stream})
}

type API_SendClientStreamLocalServer interface {
	SendAndClose(*Response) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type aPISendClientStreamLocalServer struct {
	grpc.ServerStream
}

func (x *aPISendClientStreamLocalServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendClientStreamLocalServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendServerStreamLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Message)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SendServerStreamLocal(m, &aPISendServerStreamLocalServer{stream})
}

type API_SendServerStreamLocalServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type aPISendServerStreamLocalServer struct {
	grpc.ServerStream
}

func (x *aPISendServerStreamLocalServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SendStreamLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendStreamLocal(&aPISendStreamLocalServer{stream})
}

type API_SendStreamLocalServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type aPISendStreamLocalServer struct {
	grpc.ServerStream
}

func (x *aPISendStreamLocalServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendStreamLocalServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRemote",
			Handler:    _API_SendRemote_Handler,
		},
		{
			MethodName: "SendLocal",
			Handler:    _API_SendLocal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendClientStreamRemote",
			Handler:       _API_SendClientStreamRemote_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendServerStreamRemote",
			Handler:       _API_SendServerStreamRemote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendStreamRemote",
			Handler:       _API_SendStreamRemote_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendClientStreamLocal",
			Handler:       _API_SendClientStreamLocal_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendServerStreamLocal",
			Handler:       _API_SendServerStreamLocal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendStreamLocal",
			Handler:       _API_SendStreamLocal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
