// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: grpc.proto

package builder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	API_Send_FullMethodName                 = "/builder.API/Send"
	API_SendClientStream_FullMethodName     = "/builder.API/SendClientStream"
	API_SendServerStream_FullMethodName     = "/builder.API/SendServerStream"
	API_SendFullDuplexStream_FullMethodName = "/builder.API/SendFullDuplexStream"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	Send(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error)
	SendClientStream(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamClient, error)
	SendServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (API_SendServerStreamClient, error)
	SendFullDuplexStream(ctx context.Context, opts ...grpc.CallOption) (API_SendFullDuplexStreamClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Send(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, API_Send_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SendClientStream(ctx context.Context, opts ...grpc.CallOption) (API_SendClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], API_SendClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendClientStreamClient{stream}
	return x, nil
}

type API_SendClientStreamClient interface {
	Send(*RequestMessage) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type aPISendClientStreamClient struct {
	grpc.ClientStream
}

func (x *aPISendClientStreamClient) Send(m *RequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendClientStreamClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (API_SendServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[1], API_SendServerStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SendServerStreamClient interface {
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type aPISendServerStreamClient struct {
	grpc.ClientStream
}

func (x *aPISendServerStreamClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendFullDuplexStream(ctx context.Context, opts ...grpc.CallOption) (API_SendFullDuplexStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[2], API_SendFullDuplexStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendFullDuplexStreamClient{stream}
	return x, nil
}

type API_SendFullDuplexStreamClient interface {
	Send(*RequestMessage) error
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type aPISendFullDuplexStreamClient struct {
	grpc.ClientStream
}

func (x *aPISendFullDuplexStreamClient) Send(m *RequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendFullDuplexStreamClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	Send(context.Context, *RequestMessage) (*Response, error)
	SendClientStream(API_SendClientStreamServer) error
	SendServerStream(*RequestMessage, API_SendServerStreamServer) error
	SendFullDuplexStream(API_SendFullDuplexStreamServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) Send(context.Context, *RequestMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedAPIServer) SendClientStream(API_SendClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendClientStream not implemented")
}
func (UnimplementedAPIServer) SendServerStream(*RequestMessage, API_SendServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendServerStream not implemented")
}
func (UnimplementedAPIServer) SendFullDuplexStream(API_SendFullDuplexStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFullDuplexStream not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Send(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SendClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendClientStream(&aPISendClientStreamServer{stream})
}

type API_SendClientStreamServer interface {
	SendAndClose(*Response) error
	Recv() (*RequestMessage, error)
	grpc.ServerStream
}

type aPISendClientStreamServer struct {
	grpc.ServerStream
}

func (x *aPISendClientStreamServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendClientStreamServer) Recv() (*RequestMessage, error) {
	m := new(RequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SendServerStream(m, &aPISendServerStreamServer{stream})
}

type API_SendServerStreamServer interface {
	Send(*ResponseMessage) error
	grpc.ServerStream
}

type aPISendServerStreamServer struct {
	grpc.ServerStream
}

func (x *aPISendServerStreamServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SendFullDuplexStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendFullDuplexStream(&aPISendFullDuplexStreamServer{stream})
}

type API_SendFullDuplexStreamServer interface {
	Send(*ResponseMessage) error
	Recv() (*RequestMessage, error)
	grpc.ServerStream
}

type aPISendFullDuplexStreamServer struct {
	grpc.ServerStream
}

func (x *aPISendFullDuplexStreamServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendFullDuplexStreamServer) Recv() (*RequestMessage, error) {
	m := new(RequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _API_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendClientStream",
			Handler:       _API_SendClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendServerStream",
			Handler:       _API_SendServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendFullDuplexStream",
			Handler:       _API_SendFullDuplexStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
