# ==============================================================================
# See https://pre-commit.com            for more information
# See https://pre-commit.com/hooks.html for more hooks
# ==============================================================================
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
  #      - id: check-yaml

  # Validación de Conventional Commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]

  # Golang pre-commit hooks
  # https://golangci-lint.run/welcome/install/#local-installation
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        pass_filenames: false
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        types: [go]

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false
        types: [go]

  - repo: local
    hooks:
      - id: terraform_init
        name: terraform init
        entry: pwsh -NoProfile -Command "Set-Location terraform; terraform init"
        language: system
        pass_filenames: false
        files: ^terraform/

      - id: terraform_fmt
        name: terraform fmt
        entry: pwsh -NoProfile -Command "Set-Location terraform; terraform fmt -recursive"
        language: system
        pass_filenames: false
        files: ^terraform/

      - id: terraform_validate
        name: terraform validate
        entry: pwsh -NoProfile -Command "Set-Location terraform; terraform validate"
        language: system
        pass_filenames: false
        files: ^terraform/
