
services:
  app:
    extends:
      file: ./docker/dominus/docker-compose.yml
      service: dominus

  worker:
    extends:
      file: ./docker/sidecar/docker-compose.yml
      service: sidecar


  trazabilty:
    extends:
      file: ./docker/prometheus/docker-compose.yml
      service: prometheus


  dashboard:
    extends:
     file: ./docker/grafana/docker-compose.yml
     service: grafana

  memory:
    extends:
      file: ./docker/redis/docker-compose.yml
      service: redis

networks:
  dominus:
    driver: bridge
