FROM golang:1.23-alpine3.20 as builder 

WORKDIR /app
COPY . .
RUN go mod tidy && \ 
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ./dominus


FROM alpine:3.20 as deployment 
WORKDIR /app 

ENV API_TOKEN="dominus_example_@10102024KeyServerToken"
ENV REST_PORT=8000
ENV GRPC_PORT=5000
ENV SSL_CERT="/etc/dominus/certs/cert.pem"
ENV SSL_CA="/etc/dominus/certs/ca_cert.pem"
ENV KEY_FILE="/etc/dominus/certs/cert.key"
ENV LOGS="/var/dominus/logs"
ENV WRITE_TIMEOUT=3
ENV READ_TIMEOUT=3
ENV IDLE_TIMOUT=0
ENV MAX_CONNS_PER_IP=100
ENV MAX_REQUEST_PER_CONN=100
ENV MAX_REQUEST_BODY_SIZE=50
ENV REDUCE_MEMORY_USAGE=0
ENV DISABLE_PREPARSE_MULTIPART_FORM=0
ENV DISABLE_HEADER_NAMES_NORMALIZING=0
ENV SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDEED=0
ENV NO_DEFAULT_DATE=0
ENV KEEP_HIJACKED_CONNS=0
ENV CLOSE_ON_SHUTDOWN=1
ENV STREAM_REQUEST_BODY=1
ENV DSN="mongodb://dominus:dominus10102024%408807@dominus_db:27017/admin"
ENV CIDR="0.0.0.0/0"
ENV DATABASE="prod"
ENV COLLECTIONS="logs"


COPY --from=builder /app/dominus ./dominus  
RUN addgroup -S appgroup && adduser -S appuser -G appgroup && \
    chown appuser:appgroup ./dominus
RUN mkdir -p /var/dominus/logs && \
    chown -R appuser:appgroup /var/dominus/logs
RUN mkdir -p /etc/dominus/certs && \
    chown -R appuser:appgroup /etc/dominus/certs

USER appuser 
EXPOSE ${REST_PORT} 
EXPOSE ${GRPC_PORT}

CMD ["sh","-c", "./dominus -prod=true migrate && ./dominus -prod=true start"]