FROM golang:1.24-alpine3.21 as builder 

WORKDIR /app
COPY . .
RUN go mod tidy && \ 
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ./dominus


FROM alpine:3.20 as deployment 
WORKDIR /app 


ENV REST_PORT=8000
ENV GRPC_PORT=5000

COPY --from=builder /app/dominus ./dominus  
RUN addgroup -S appgroup && adduser -S appuser -G appgroup && \
    chown appuser:appgroup ./dominus
RUN mkdir -p /var/dominus/logs && \
    chown -R appuser:appgroup /var/dominus/logs
RUN mkdir -p /etc/dominus/certs && \
    chown -R appuser:appgroup /etc/dominus/certs

USER appuser 
EXPOSE ${REST_PORT} 
EXPOSE ${GRPC_PORT}

CMD ["sh","-c", "./dominus -prod=true -banner=false"]