apiVersion: v1
kind: Secret
metadata:
  name: dominus-config
  namespace: default
type: Opaque
data:
  API_TOKEN: ZG9taW51c19leGFtcGxlX0AxMDEwMjAyNEtleVNlcnZlclRva2Vu
  HOST: bG9jYWxob3N0OjgwMDA=
  REST_PORT: ODAwMA==
  GRPC_PORT: NTAwMA==
  SSL_CERT: L2V0Yy9kb21pbnVzL2NlcnRzL2NlcnQucGVt
  SSL_CA: L2V0Yy9kb21pbnVzL2NlcnRzL2NhX2NlcnQucGVt
  KEY_FILE: L2V0Yy9kb21pbnVzL2NlcnRzL2NlcnQua2V5
  LOGS: L3Zhci9kb21pbnVzL2xvZ3M=
  ALLOW_ORIGINS: MC4wLjAuMC8yNA==   
  TOPIC_LIMIT: MTAw
