apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominus
  namespace: default
  labels:
    app: dominus
spec:
  selector:
    matchLabels:
      app: dominus
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dominus
    spec:
      containers:
        - name: dominus
          image: dominus:kubernetes
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 3Gi
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "wget -qO- --header='x-api-key: dominus_example_@10102024KeyServerToken' http://127.0.0.1:8000/health"
            initialDelaySeconds: 60
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 60

          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: API_TOKEN

            - name: REST_PORT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: REST_PORT

            - name: GRPC_PORT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: GRPC_PORT

            - name: SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: SSL_CERT

            - name: SSL_CA
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: SSL_CA

            - name: KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: KEY_FILE

            - name: LOGS
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: LOGS

            - name: WRITE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: WRITE_TIMEOUT

            - name: READ_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: READ_TIMEOUT

            - name: IDLE_TIMOUT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: IDLE_TIMOUT

            - name: MAX_CONNS_PER_IP
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: MAX_CONNS_PER_IP

            - name: MAX_REQUEST_PER_CONN
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: MAX_REQUEST_PER_CONN

            - name: MAX_REQUEST_BODY_SIZE
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: MAX_REQUEST_BODY_SIZE

            - name: REDUCE_MEMORY_USAGE
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: REDUCE_MEMORY_USAGE

            - name: DISABLE_HEADER_NAMES_NORMALIZING
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: DISABLE_HEADER_NAMES_NORMALIZING

            - name: SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDED
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDED

            - name: NO_DEFAULT_DATE
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: NO_DEFAULT_DATE

            - name: KEEP_HIJACKED_CONNS
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: KEEP_HIJACKED_CONNS

            - name: CLOSE_ON_SHUTDOWN
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: CLOSE_ON_SHUTDOWN

            - name: STREAM_REQUEST_BODY
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: STREAM_REQUEST_BODY

            - name: CIDR
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: CIDR

          ports:
            - containerPort: 8000
              name: rest
            - containerPort: 5000
              name: grpc

          volumeMounts:
            - name: dominus-certs
              mountPath: /etc/dominus/certs
              readOnly: true
            - name: dominus-logs
              mountPath: /var/dominus/logs
              readOnly: false

      volumes:
        - name: dominus-certs
          persistentVolumeClaim:
            claimName: dominus-certs-pvc
        - name: dominus-logs
          persistentVolumeClaim:
            claimName: dominus-logs-pvc

      restartPolicy: Always


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dominus-certs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Ki

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dominus-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 


---
apiVersion: v1
kind: Service
metadata:
  name: dominus-rest
  namespace: default
spec:
  selector:
    app: dominus
  sessionAffinity: None
  type: LoadBalancer
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: rest
      protocol: TCP
      port: 8000
      targetPort: 8000 
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000