apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominus
  namespace: default
  labels:
    app: dominus
spec:
  selector:
    matchLabels:
      app: dominus
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dominus
    spec:
      containers:
        - name: dominus
          image: dominus:kubernetes
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 3Gi
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "wget -qO- --header='x-api-key: dominus_example_@10102024KeyServerToken' http://127.0.0.1:8000/health"
            initialDelaySeconds: 60
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 60

          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: API_TOKEN

            - name: REST_PORT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: REST_PORT

            - name: GRPC_PORT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: GRPC_PORT

            - name: SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: SSL_CERT

            - name: SSL_CA
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: SSL_CA

            - name: KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: KEY_FILE

            - name: LOGS
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: LOGS

            - name: ALLOW_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: dominus-config
                  key: ALLOW_ORIGINS

          ports:
            - containerPort: 8000
              name: rest
            - containerPort: 5000
              name: grpc

          volumeMounts:
            - name: dominus-certs
              mountPath: /etc/dominus/certs
              readOnly: true
            - name: dominus-logs
              mountPath: /var/dominus/logs
              readOnly: false

      volumes:
        - name: dominus-certs
          persistentVolumeClaim:
            claimName: dominus-certs-pvc
        - name: dominus-logs
          persistentVolumeClaim:
            claimName: dominus-logs-pvc

      restartPolicy: Always


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dominus-certs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Ki

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dominus-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 


---
apiVersion: v1
kind: Service
metadata:
  name: dominus-rest
  namespace: default
spec:
  selector:
    app: dominus
  sessionAffinity: None
  type: LoadBalancer
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: rest
      protocol: TCP
      port: 8000
      targetPort: 8000 
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000