# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: IngressName
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
    - host: grafana.dominus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000

    - host: prometheus.dominus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090

    - host: api.dominus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dominus-service-rest
                port:
                  number: 8000

    - host: grpc.dominus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dominus-service-grpc
                port:
                  number: 5000
