apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dominus-dep.yml
  - sidecar-dep.yml
  - prometheus-dep.yml  

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf=nginx.conf
  - name: prometheus-config
    files:
      - prometheus.yml