apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-config
  namespace: default
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http { 
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        error_log /var/log/nginx/error.log error;
        access_log /var/log/nginx/access.log;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/conf.d/*.conf;
        client_max_body_size 50m;
        connection_pool_size 512;

        server {
            listen 80;
            server_name sidecar;
            proxy_http_version 1.1;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_pass_request_headers on;
            proxy_pass_request_body on;
            underscores_in_headers on;
            http2 on;
            http3 on;
            autoindex off;

            location /metrics {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header API_TOKEN "dominus_example_@10102024KeyServerToken";
                proxy_pass http://dominus-rest:8000/metrics;
            }
        }
    }
