apiVersion: v1
kind: Secret
metadata:
  name: dominus-config
  namespace: default
type: Opaque
data:
    API_TOKEN: {{.Values.dominus.API_TOKEN | b64enc }}
    REST_PORT: {{ .Values.dominus.REST_PORT | b64enc }}
    GRPC_PORT: {{ .Values.dominus.GRPC_PORT | b64enc }}
    SSL_CERT: {{ .Values.dominus.SSL_CERT | b64enc }}
    SSL_CA: {{ .Values.dominus. SSL_CA | b64enc }}
    KEY_FILE: {{ .Values.dominus.KEY_FILE | b64enc }}
    LOGS: {{ .Values.dominus.LOGS | b64enc }}
    WRITE_TIMEOUT: {{ .Values.dominus.WRITE_TIMEOUT | b64enc }}
    READ_TIMEOUT: {{ .Values.dominus.READ_TIMEOUT | b64enc }}
    IDLE_TIMOUT: {{ .Values.dominus.IDLE_TIMOUT | b64enc }}
    MAX_CONNS_PER_IP: {{ .Values.dominus.MAX_CONNS_PER_IP | b64enc }}
    MAX_REQUEST_PER_CONN: {{ .Values.dominus.MAX_REQUEST_PER_CONN | b64enc }}
    MAX_REQUEST_BODY_SIZE: {{ .Values.dominus. MAX_REQUEST_BODY_SIZE | b64enc }}
    REDUCE_MEMORY_USAGE: {{ .Values.dominus.REDUCE_MEMORY_USAGE | b64enc }}
    DISABLE_PREPARSE_MULTIPART_FORM: {{ .Values.dominus.DISABLE_PREPARSE_MULTIPART_FORM | b64enc }}
    DISABLE_HEADER_NAMES_NORMALIZING: {{ .Values.dominus.DISABLE_HEADER_NAMES_NORMALIZING | b64enc }}
    SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDEED: {{ .Values.dominus.SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDEED | b64enc }}
    NO_DEFAULT_DATE: {{ .Values.dominus.NO_DEFAULT_DATE | b64enc }}
    KEEP_HIJACKED_CONNS: {{ .Values.dominus.KEEP_HIJACKED_CONNS | b64enc }}
    CLOSE_ON_SHUTDOWN: {{ .Values.dominus.CLOSE_ON_SHUTDOWN | b64enc }}
    STREAM_REQUEST_BODY: {{ .Values.dominus.STREAM_REQUEST_BODY | b64enc }}
    CIDR: {{ .Values.dominus.CIDR | b64enc }}