apiVersion: v1
kind: Secret
metadata:
  name: dominus-config
  namespace: default
type: Opaque
data:
  API_TOKEN: ZG9taW51c19leGFtcGxlX0AxMDEwMjAyNEtleVNlcnZlclRva2Vu
  HOST: bG9jYWxob3N0OjgwMDA=
  REST_PORT: ODAwMA==
  GRPC_PORT: NTAwMA==
  SSL_CERT: L2V0Yy9kb21pbnVzL2NlcnRzL2NlcnQucGVt
  SSL_CA: L2V0Yy9kb21pbnVzL2NlcnRzL2NhX2NlcnQucGVt
  KEY_FILE: L2V0Yy9kb21pbnVzL2NlcnRzL2NlcnQua2V5
  LOGS: L3Zhci9kb21pbnVzL2xvZ3M=
  WRITE_TIMEOUT: Mw==
  READ_TIMEOUT: Mw==
  IDLE_TIMOUT: MA==
  MAX_CONNS_PER_IP: MTAw
  MAX_REQUEST_PER_CONN: MTAw
  MAX_REQUEST_BODY_SIZE: NTA=
  REDUCE_MEMORY_USAGE: MA==
  DISABLE_PREPARSE_MULTIPART_FORM: MA==
  DISABLE_HEADER_NAMES_NORMALIZING: MA==
  SLEEP_WHEN_CONCURRENCY_LIMIT_EXCEDED: MA==
  NO_DEFAULT_DATE: MA==
  KEEP_HIJACKED_CONNS: MA==
  CLOSE_ON_SHUTDOWN: MQ==
  STREAM_REQUEST_BODY: MQ==
  ALLOW_ORIGINS: aHR0cDovL2xvY2FsaG9zdDo4MDAw
