version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dominus_db
    
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    
    environment:
      - MONGO_INITDB_DATABASE=dominus
      - MONGO_INITDB_ROOT_USERNAME=dominus
      - MONGO_INITDB_ROOT_PASSWORD=dominus1234

    volumes:
      - ./database:/data/db
    command: [--auth]

    ports:
      - 27017:27017
    networks:
      - dominus

volumes:
  database:

networks:
  dominus:
    driver: overlay
    attachable: true
    external: true