// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repositories/queue.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repositories/queue.go -destination=./mocks/mock_queue.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "dominus-project/internal/domain/entities"
	services "dominus-project/internal/domain/services"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemoryClient is a mock of MemoryClient interface.
type MockMemoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryClientMockRecorder
	isgomock struct{}
}

// MockMemoryClientMockRecorder is the mock recorder for MockMemoryClient.
type MockMemoryClientMockRecorder struct {
	mock *MockMemoryClient
}

// NewMockMemoryClient creates a new mock instance.
func NewMockMemoryClient(ctrl *gomock.Controller) *MockMemoryClient {
	mock := &MockMemoryClient{ctrl: ctrl}
	mock.recorder = &MockMemoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryClient) EXPECT() *MockMemoryClientMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMemoryClient) DeleteMessage(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMemoryClientMockRecorder) DeleteMessage(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMemoryClient)(nil).DeleteMessage), ctx, ID)
}

// GetKeys mocks base method.
func (m *MockMemoryClient) GetKeys(ctx context.Context, mem services.Memory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, mem)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockMemoryClientMockRecorder) GetKeys(ctx, mem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockMemoryClient)(nil).GetKeys), ctx, mem)
}

// GetMessage mocks base method.
func (m *MockMemoryClient) GetMessage(ctx context.Context, key string) (*entities.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, key)
	ret0, _ := ret[0].(*entities.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMemoryClientMockRecorder) GetMessage(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMemoryClient)(nil).GetMessage), ctx, key)
}

// SendMessage mocks base method.
func (m *MockMemoryClient) SendMessage(ctx context.Context, q *entities.Queue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMemoryClientMockRecorder) SendMessage(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMemoryClient)(nil).SendMessage), ctx, q)
}

// MockCheckerClient is a mock of CheckerClient interface.
type MockCheckerClient struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerClientMockRecorder
	isgomock struct{}
}

// MockCheckerClientMockRecorder is the mock recorder for MockCheckerClient.
type MockCheckerClientMockRecorder struct {
	mock *MockCheckerClient
}

// NewMockCheckerClient creates a new mock instance.
func NewMockCheckerClient(ctrl *gomock.Controller) *MockCheckerClient {
	mock := &MockCheckerClient{ctrl: ctrl}
	mock.recorder = &MockCheckerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckerClient) EXPECT() *MockCheckerClientMockRecorder {
	return m.recorder
}

// CheckConsumer mocks base method.
func (m *MockCheckerClient) CheckConsumer(ctx context.Context, key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConsumer", ctx, key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckConsumer indicates an expected call of CheckConsumer.
func (mr *MockCheckerClientMockRecorder) CheckConsumer(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConsumer", reflect.TypeOf((*MockCheckerClient)(nil).CheckConsumer), ctx, key)
}

// SaveConsumer mocks base method.
func (m *MockCheckerClient) SaveConsumer(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConsumer", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConsumer indicates an expected call of SaveConsumer.
func (mr *MockCheckerClientMockRecorder) SaveConsumer(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConsumer", reflect.TypeOf((*MockCheckerClient)(nil).SaveConsumer), ctx, key)
}
