// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/grpc_request.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/grpc_request.go -destination=mocks/mock_grpc_request.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGrpcDto is a mock of GrpcDto interface.
type MockGrpcDto struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcDtoMockRecorder
	isgomock struct{}
}

// MockGrpcDtoMockRecorder is the mock recorder for MockGrpcDto.
type MockGrpcDtoMockRecorder struct {
	mock *MockGrpcDto
}

// NewMockGrpcDto creates a new mock instance.
func NewMockGrpcDto(ctrl *gomock.Controller) *MockGrpcDto {
	mock := &MockGrpcDto{ctrl: ctrl}
	mock.recorder = &MockGrpcDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcDto) EXPECT() *MockGrpcDtoMockRecorder {
	return m.recorder
}

// GetPayload mocks base method.
func (m *MockGrpcDto) GetPayload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockGrpcDtoMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockGrpcDto)(nil).GetPayload))
}

// GetSubscribers mocks base method.
func (m *MockGrpcDto) GetSubscribers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockGrpcDtoMockRecorder) GetSubscribers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockGrpcDto)(nil).GetSubscribers))
}
