// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\consumer\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\consumer\factory.go -destination=.\mocks\mock_usecases_consumer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	consumer "dominus-broker/internal/application/usecases/consumer"
	entities "dominus-broker/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConsumerUseCase is a mock of ConsumerUseCase interface.
type MockConsumerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerUseCaseMockRecorder
	isgomock struct{}
}

// MockConsumerUseCaseMockRecorder is the mock recorder for MockConsumerUseCase.
type MockConsumerUseCaseMockRecorder struct {
	mock *MockConsumerUseCase
}

// NewMockConsumerUseCase creates a new mock instance.
func NewMockConsumerUseCase(ctrl *gomock.Controller) *MockConsumerUseCase {
	mock := &MockConsumerUseCase{ctrl: ctrl}
	mock.recorder = &MockConsumerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerUseCase) EXPECT() *MockConsumerUseCaseMockRecorder {
	return m.recorder
}

// Consumer mocks base method.
func (m *MockConsumerUseCase) Consumer(ctx context.Context, ms consumer.ConsumerDto) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumer", ctx, ms)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consumer indicates an expected call of Consumer.
func (mr *MockConsumerUseCaseMockRecorder) Consumer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumer", reflect.TypeOf((*MockConsumerUseCase)(nil).Consumer), ctx, ms)
}
