// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repositories/broker.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repositories/broker.go -destination=./mocks/mock_broker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerClient is a mock of BrokerClient interface.
type MockBrokerClient struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerClientMockRecorder
	isgomock struct{}
}

// MockBrokerClientMockRecorder is the mock recorder for MockBrokerClient.
type MockBrokerClientMockRecorder struct {
	mock *MockBrokerClient
}

// NewMockBrokerClient creates a new mock instance.
func NewMockBrokerClient(ctrl *gomock.Controller) *MockBrokerClient {
	mock := &MockBrokerClient{ctrl: ctrl}
	mock.recorder = &MockBrokerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerClient) EXPECT() *MockBrokerClientMockRecorder {
	return m.recorder
}

// BidirectionalStream mocks base method.
func (m *MockBrokerClient) BidirectionalStream(urls []string, provMsg <-chan []byte, subMsg chan<- []byte, errMsg chan<- error, tx chan<- struct{}, ctx context.Context, done chan<- struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BidirectionalStream", urls, provMsg, subMsg, errMsg, tx, ctx, done)
}

// BidirectionalStream indicates an expected call of BidirectionalStream.
func (mr *MockBrokerClientMockRecorder) BidirectionalStream(urls, provMsg, subMsg, errMsg, tx, ctx, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStream", reflect.TypeOf((*MockBrokerClient)(nil).BidirectionalStream), urls, provMsg, subMsg, errMsg, tx, ctx, done)
}

// ClientStream mocks base method.
func (m *MockBrokerClient) ClientStream(urls []string, msg <-chan []byte, ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClientStream", urls, msg, ctx)
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockBrokerClientMockRecorder) ClientStream(urls, msg, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockBrokerClient)(nil).ClientStream), urls, msg, ctx)
}

// ServerStream mocks base method.
func (m *MockBrokerClient) ServerStream(urls []string, initalMsg []byte, msg chan<- []byte, ctx context.Context, done chan<- struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServerStream", urls, initalMsg, msg, ctx, done)
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockBrokerClientMockRecorder) ServerStream(urls, initalMsg, msg, ctx, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockBrokerClient)(nil).ServerStream), urls, initalMsg, msg, ctx, done)
}
