// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_bidirectional\dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_bidirectional\dto.go -destination=.\mocks\mock_dto_stream_bidirectional.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "dominus-broker/internal/application/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerBidirectionalDto is a mock of BrokerBidirectionalDto interface.
type MockBrokerBidirectionalDto struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerBidirectionalDtoMockRecorder
	isgomock struct{}
}

// MockBrokerBidirectionalDtoMockRecorder is the mock recorder for MockBrokerBidirectionalDto.
type MockBrokerBidirectionalDtoMockRecorder struct {
	mock *MockBrokerBidirectionalDto
}

// NewMockBrokerBidirectionalDto creates a new mock instance.
func NewMockBrokerBidirectionalDto(ctrl *gomock.Controller) *MockBrokerBidirectionalDto {
	mock := &MockBrokerBidirectionalDto{ctrl: ctrl}
	mock.recorder = &MockBrokerBidirectionalDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerBidirectionalDto) EXPECT() *MockBrokerBidirectionalDtoMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockBrokerBidirectionalDto) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBrokerBidirectionalDtoMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBrokerBidirectionalDto)(nil).Context))
}

// Recv mocks base method.
func (m *MockBrokerBidirectionalDto) Recv() (dto.BrokerRequestDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(dto.BrokerRequestDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockBrokerBidirectionalDtoMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockBrokerBidirectionalDto)(nil).Recv))
}

// Send mocks base method.
func (m *MockBrokerBidirectionalDto) Send(msg []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBrokerBidirectionalDtoMockRecorder) Send(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBrokerBidirectionalDto)(nil).Send), msg)
}
