// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\ack\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\ack\factory.go -destination=.\mocks\mock_usecases_ack.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	ack "dominus-broker/internal/application/usecases/ack"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAckUseCase is a mock of AckUseCase interface.
type MockAckUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAckUseCaseMockRecorder
	isgomock struct{}
}

// MockAckUseCaseMockRecorder is the mock recorder for MockAckUseCase.
type MockAckUseCaseMockRecorder struct {
	mock *MockAckUseCase
}

// NewMockAckUseCase creates a new mock instance.
func NewMockAckUseCase(ctrl *gomock.Controller) *MockAckUseCase {
	mock := &MockAckUseCase{ctrl: ctrl}
	mock.recorder = &MockAckUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAckUseCase) EXPECT() *MockAckUseCaseMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockAckUseCase) Ack(ctx context.Context, ms ack.AskDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockAckUseCaseMockRecorder) Ack(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockAckUseCase)(nil).Ack), ctx, ms)
}
