// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_bidirectional\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_bidirectional\factory.go -destination=.\mocks\mock_usecases_stream_bidirectional.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	streambidirectional "dominus-broker/internal/application/usecases/stream_bidirectional"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamBidirectionalUseCase is a mock of StreamBidirectionalUseCase interface.
type MockStreamBidirectionalUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStreamBidirectionalUseCaseMockRecorder
	isgomock struct{}
}

// MockStreamBidirectionalUseCaseMockRecorder is the mock recorder for MockStreamBidirectionalUseCase.
type MockStreamBidirectionalUseCaseMockRecorder struct {
	mock *MockStreamBidirectionalUseCase
}

// NewMockStreamBidirectionalUseCase creates a new mock instance.
func NewMockStreamBidirectionalUseCase(ctrl *gomock.Controller) *MockStreamBidirectionalUseCase {
	mock := &MockStreamBidirectionalUseCase{ctrl: ctrl}
	mock.recorder = &MockStreamBidirectionalUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamBidirectionalUseCase) EXPECT() *MockStreamBidirectionalUseCaseMockRecorder {
	return m.recorder
}

// StreamBidirectional mocks base method.
func (m *MockStreamBidirectionalUseCase) StreamBidirectional(st streambidirectional.BrokerBidirectionalDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamBidirectional", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamBidirectional indicates an expected call of StreamBidirectional.
func (mr *MockStreamBidirectionalUseCaseMockRecorder) StreamBidirectional(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBidirectional", reflect.TypeOf((*MockStreamBidirectionalUseCase)(nil).StreamBidirectional), st)
}
