// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructure/event/event.go
//
// Generated by this command:
//
//	mockgen -source=./internal/infrastructure/event/event.go -destination=./mocks/mock_infrastructure_event.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// CheckID mocks base method.
func (m *MockEvent) CheckID(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckID", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// CheckID indicates an expected call of CheckID.
func (mr *MockEventMockRecorder) CheckID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckID", reflect.TypeOf((*MockEvent)(nil).CheckID), ctx)
}

// WriteLog mocks base method.
func (m *MockEvent) WriteLog(ctx context.Context, level, op, dsc string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteLog", ctx, level, op, dsc)
}

// WriteLog indicates an expected call of WriteLog.
func (mr *MockEventMockRecorder) WriteLog(ctx, level, op, dsc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLog", reflect.TypeOf((*MockEvent)(nil).WriteLog), ctx, level, op, dsc)
}
