// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_server\dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_server\dto.go -destination=.\mocks\mock_dto_stream_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerRequestDto is a mock of BrokerRequestDto interface.
type MockBrokerRequestDto struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerRequestDtoMockRecorder
	isgomock struct{}
}

// MockBrokerRequestDtoMockRecorder is the mock recorder for MockBrokerRequestDto.
type MockBrokerRequestDtoMockRecorder struct {
	mock *MockBrokerRequestDto
}

// NewMockBrokerRequestDto creates a new mock instance.
func NewMockBrokerRequestDto(ctrl *gomock.Controller) *MockBrokerRequestDto {
	mock := &MockBrokerRequestDto{ctrl: ctrl}
	mock.recorder = &MockBrokerRequestDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerRequestDto) EXPECT() *MockBrokerRequestDtoMockRecorder {
	return m.recorder
}

// GetPayload mocks base method.
func (m *MockBrokerRequestDto) GetPayload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockBrokerRequestDtoMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockBrokerRequestDto)(nil).GetPayload))
}

// GetSubscribers mocks base method.
func (m *MockBrokerRequestDto) GetSubscribers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockBrokerRequestDtoMockRecorder) GetSubscribers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockBrokerRequestDto)(nil).GetSubscribers))
}

// MockBrokerServerDto is a mock of BrokerServerDto interface.
type MockBrokerServerDto struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerServerDtoMockRecorder
	isgomock struct{}
}

// MockBrokerServerDtoMockRecorder is the mock recorder for MockBrokerServerDto.
type MockBrokerServerDtoMockRecorder struct {
	mock *MockBrokerServerDto
}

// NewMockBrokerServerDto creates a new mock instance.
func NewMockBrokerServerDto(ctrl *gomock.Controller) *MockBrokerServerDto {
	mock := &MockBrokerServerDto{ctrl: ctrl}
	mock.recorder = &MockBrokerServerDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerServerDto) EXPECT() *MockBrokerServerDtoMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockBrokerServerDto) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBrokerServerDtoMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBrokerServerDto)(nil).Context))
}

// Send mocks base method.
func (m *MockBrokerServerDto) Send(payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBrokerServerDtoMockRecorder) Send(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBrokerServerDto)(nil).Send), payload)
}
