// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/grpc_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/grpc_client.go -destination=mocks/mock_grpc_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	adapters "dominus-project/internal/domain/adapters"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGrpcClient is a mock of GrpcClient interface.
type MockGrpcClient struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcClientMockRecorder
	isgomock struct{}
}

// MockGrpcClientMockRecorder is the mock recorder for MockGrpcClient.
type MockGrpcClientMockRecorder struct {
	mock *MockGrpcClient
}

// NewMockGrpcClient creates a new mock instance.
func NewMockGrpcClient(ctrl *gomock.Controller) *MockGrpcClient {
	mock := &MockGrpcClient{ctrl: ctrl}
	mock.recorder = &MockGrpcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcClient) EXPECT() *MockGrpcClientMockRecorder {
	return m.recorder
}

// BidirectionalStream mocks base method.
func (m *MockGrpcClient) BidirectionalStream(urls []string, provMsg <-chan []byte, subMsg chan<- []byte, errMsg chan<- error, tx chan<- struct{}, ctx context.Context, done chan<- struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BidirectionalStream", urls, provMsg, subMsg, errMsg, tx, ctx, done)
}

// BidirectionalStream indicates an expected call of BidirectionalStream.
func (mr *MockGrpcClientMockRecorder) BidirectionalStream(urls, provMsg, subMsg, errMsg, tx, ctx, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStream", reflect.TypeOf((*MockGrpcClient)(nil).BidirectionalStream), urls, provMsg, subMsg, errMsg, tx, ctx, done)
}

// ClientStream mocks base method.
func (m *MockGrpcClient) ClientStream(urls []string, msg <-chan []byte, ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClientStream", urls, msg, ctx)
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockGrpcClientMockRecorder) ClientStream(urls, msg, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockGrpcClient)(nil).ClientStream), urls, msg, ctx)
}

// ServerStream mocks base method.
func (m *MockGrpcClient) ServerStream(urls []string, initalMsg []byte, msg chan<- []byte, ctx context.Context, done chan<- struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServerStream", urls, initalMsg, msg, ctx, done)
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockGrpcClientMockRecorder) ServerStream(urls, initalMsg, msg, ctx, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockGrpcClient)(nil).ServerStream), urls, initalMsg, msg, ctx, done)
}

// Simple mocks base method.
func (m *MockGrpcClient) Simple(url string, msg []byte) (adapters.GrpcResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Simple", url, msg)
	ret0, _ := ret[0].(adapters.GrpcResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Simple indicates an expected call of Simple.
func (mr *MockGrpcClientMockRecorder) Simple(url, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Simple", reflect.TypeOf((*MockGrpcClient)(nil).Simple), url, msg)
}
