// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/stream_server.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/stream_server.go -destination=mocks/mock_stream_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamServer is a mock of StreamServer interface.
type MockStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServerMockRecorder
	isgomock struct{}
}

// MockStreamServerMockRecorder is the mock recorder for MockStreamServer.
type MockStreamServerMockRecorder struct {
	mock *MockStreamServer
}

// NewMockStreamServer creates a new mock instance.
func NewMockStreamServer(ctrl *gomock.Controller) *MockStreamServer {
	mock := &MockStreamServer{ctrl: ctrl}
	mock.recorder = &MockStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamServer) EXPECT() *MockStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStreamServer)(nil).Context))
}

// Send mocks base method.
func (m *MockStreamServer) Send(payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamServerMockRecorder) Send(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStreamServer)(nil).Send), payload)
}
