// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interactors/grpc_conn/factory.go
//
// Generated by this command:
//
//	mockgen -source=internal/interactors/grpc_conn/factory.go -destination=mocks/mock_grpc_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	adapters "dominus-project/internal/domain/adapters"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGrpcService is a mock of GrpcService interface.
type MockGrpcService struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcServiceMockRecorder
	isgomock struct{}
}

// MockGrpcServiceMockRecorder is the mock recorder for MockGrpcService.
type MockGrpcServiceMockRecorder struct {
	mock *MockGrpcService
}

// NewMockGrpcService creates a new mock instance.
func NewMockGrpcService(ctrl *gomock.Controller) *MockGrpcService {
	mock := &MockGrpcService{ctrl: ctrl}
	mock.recorder = &MockGrpcServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcService) EXPECT() *MockGrpcServiceMockRecorder {
	return m.recorder
}

// RunQueue mocks base method.
func (m *MockGrpcService) RunQueue(close <-chan struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunQueue", close)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunQueue indicates an expected call of RunQueue.
func (mr *MockGrpcServiceMockRecorder) RunQueue(close any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunQueue", reflect.TypeOf((*MockGrpcService)(nil).RunQueue), close)
}

// SimpleConn mocks base method.
func (m *MockGrpcService) SimpleConn(ms adapters.GrpcDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimpleConn", ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// SimpleConn indicates an expected call of SimpleConn.
func (mr *MockGrpcServiceMockRecorder) SimpleConn(ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimpleConn", reflect.TypeOf((*MockGrpcService)(nil).SimpleConn), ms)
}

// StreamBiConn mocks base method.
func (m *MockGrpcService) StreamBiConn(st adapters.StreamBi) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamBiConn", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamBiConn indicates an expected call of StreamBiConn.
func (mr *MockGrpcServiceMockRecorder) StreamBiConn(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBiConn", reflect.TypeOf((*MockGrpcService)(nil).StreamBiConn), st)
}

// StreamClientConn mocks base method.
func (m *MockGrpcService) StreamClientConn(st adapters.StreamClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamClientConn", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamClientConn indicates an expected call of StreamClientConn.
func (mr *MockGrpcServiceMockRecorder) StreamClientConn(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamClientConn", reflect.TypeOf((*MockGrpcService)(nil).StreamClientConn), st)
}

// StreamServerConn mocks base method.
func (m *MockGrpcService) StreamServerConn(req adapters.GrpcDto, st adapters.StreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamServerConn", req, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamServerConn indicates an expected call of StreamServerConn.
func (mr *MockGrpcServiceMockRecorder) StreamServerConn(req, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamServerConn", reflect.TypeOf((*MockGrpcService)(nil).StreamServerConn), req, st)
}
