// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\dtos\sqs_dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\dtos\sqs_dto.go -destination=.\mocks\mock_dtos_sqs.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerDto is a mock of ProducerDto interface.
type MockProducerDto struct {
	ctrl     *gomock.Controller
	recorder *MockProducerDtoMockRecorder
	isgomock struct{}
}

// MockProducerDtoMockRecorder is the mock recorder for MockProducerDto.
type MockProducerDtoMockRecorder struct {
	mock *MockProducerDto
}

// NewMockProducerDto creates a new mock instance.
func NewMockProducerDto(ctrl *gomock.Controller) *MockProducerDto {
	mock := &MockProducerDto{ctrl: ctrl}
	mock.recorder = &MockProducerDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerDto) EXPECT() *MockProducerDtoMockRecorder {
	return m.recorder
}

// GetPayload mocks base method.
func (m *MockProducerDto) GetPayload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockProducerDtoMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockProducerDto)(nil).GetPayload))
}

// MockConsumerDto is a mock of ConsumerDto interface.
type MockConsumerDto struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerDtoMockRecorder
	isgomock struct{}
}

// MockConsumerDtoMockRecorder is the mock recorder for MockConsumerDto.
type MockConsumerDtoMockRecorder struct {
	mock *MockConsumerDto
}

// NewMockConsumerDto creates a new mock instance.
func NewMockConsumerDto(ctrl *gomock.Controller) *MockConsumerDto {
	mock := &MockConsumerDto{ctrl: ctrl}
	mock.recorder = &MockConsumerDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerDto) EXPECT() *MockConsumerDtoMockRecorder {
	return m.recorder
}

// GetGroupId mocks base method.
func (m *MockConsumerDto) GetGroupId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGroupId indicates an expected call of GetGroupId.
func (mr *MockConsumerDtoMockRecorder) GetGroupId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupId", reflect.TypeOf((*MockConsumerDto)(nil).GetGroupId))
}

// GetId mocks base method.
func (m *MockConsumerDto) GetId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockConsumerDtoMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockConsumerDto)(nil).GetId))
}

// GetWorker mocks base method.
func (m *MockConsumerDto) GetWorker() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorker")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWorker indicates an expected call of GetWorker.
func (mr *MockConsumerDtoMockRecorder) GetWorker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorker", reflect.TypeOf((*MockConsumerDto)(nil).GetWorker))
}
