// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_server\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_server\factory.go -destination=.\mocks\mock_usecases_stream_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	streamserver "dominus-broker/internal/application/usecases/stream_server"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamServerUseCase is a mock of StreamServerUseCase interface.
type MockStreamServerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServerUseCaseMockRecorder
	isgomock struct{}
}

// MockStreamServerUseCaseMockRecorder is the mock recorder for MockStreamServerUseCase.
type MockStreamServerUseCaseMockRecorder struct {
	mock *MockStreamServerUseCase
}

// NewMockStreamServerUseCase creates a new mock instance.
func NewMockStreamServerUseCase(ctrl *gomock.Controller) *MockStreamServerUseCase {
	mock := &MockStreamServerUseCase{ctrl: ctrl}
	mock.recorder = &MockStreamServerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamServerUseCase) EXPECT() *MockStreamServerUseCaseMockRecorder {
	return m.recorder
}

// StreamServer mocks base method.
func (m *MockStreamServerUseCase) StreamServer(req streamserver.BrokerRequestDto, st streamserver.BrokerServerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamServer", req, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamServer indicates an expected call of StreamServer.
func (mr *MockStreamServerUseCaseMockRecorder) StreamServer(req, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamServer", reflect.TypeOf((*MockStreamServerUseCase)(nil).StreamServer), req, st)
}
