// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_client\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_client\factory.go -destination=.\mocks\mock_usecases_stream_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	streamclient "dominus-broker/internal/application/usecases/stream_client"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamClientUseCase is a mock of StreamClientUseCase interface.
type MockStreamClientUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStreamClientUseCaseMockRecorder
	isgomock struct{}
}

// MockStreamClientUseCaseMockRecorder is the mock recorder for MockStreamClientUseCase.
type MockStreamClientUseCaseMockRecorder struct {
	mock *MockStreamClientUseCase
}

// NewMockStreamClientUseCase creates a new mock instance.
func NewMockStreamClientUseCase(ctrl *gomock.Controller) *MockStreamClientUseCase {
	mock := &MockStreamClientUseCase{ctrl: ctrl}
	mock.recorder = &MockStreamClientUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamClientUseCase) EXPECT() *MockStreamClientUseCaseMockRecorder {
	return m.recorder
}

// StreamClient mocks base method.
func (m *MockStreamClientUseCase) StreamClient(st streamclient.BrokerClientDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamClient", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamClient indicates an expected call of StreamClient.
func (mr *MockStreamClientUseCaseMockRecorder) StreamClient(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamClient", reflect.TypeOf((*MockStreamClientUseCase)(nil).StreamClient), st)
}
