// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\use_cases\sqs\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\use_cases\sqs\factory.go -destination=.\mocks\mock_usecases_sqs.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dtos "dominus-project/internal/application/dtos"
	entities "dominus-project/internal/domain/entities"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSQS is a mock of SQS interface.
type MockSQS struct {
	ctrl     *gomock.Controller
	recorder *MockSQSMockRecorder
	isgomock struct{}
}

// MockSQSMockRecorder is the mock recorder for MockSQS.
type MockSQSMockRecorder struct {
	mock *MockSQS
}

// NewMockSQS creates a new mock instance.
func NewMockSQS(ctrl *gomock.Controller) *MockSQS {
	mock := &MockSQS{ctrl: ctrl}
	mock.recorder = &MockSQSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQS) EXPECT() *MockSQSMockRecorder {
	return m.recorder
}

// CheckMemory mocks base method.
func (m *MockSQS) CheckMemory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckMemory")
}

// CheckMemory indicates an expected call of CheckMemory.
func (mr *MockSQSMockRecorder) CheckMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMemory", reflect.TypeOf((*MockSQS)(nil).CheckMemory))
}

// Consumer mocks base method.
func (m *MockSQS) Consumer(ctx context.Context) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumer", ctx)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consumer indicates an expected call of Consumer.
func (mr *MockSQSMockRecorder) Consumer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumer", reflect.TypeOf((*MockSQS)(nil).Consumer), ctx)
}

// ConsumerDLT mocks base method.
func (m *MockSQS) ConsumerDLT(ctx context.Context, ms dtos.ConsumerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerDLT", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumerDLT indicates an expected call of ConsumerDLT.
func (mr *MockSQSMockRecorder) ConsumerDLT(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerDLT", reflect.TypeOf((*MockSQS)(nil).ConsumerDLT), ctx, ms)
}

// Producer mocks base method.
func (m *MockSQS) Producer(ctx context.Context, ms dtos.ProducerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Producer", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Producer indicates an expected call of Producer.
func (mr *MockSQSMockRecorder) Producer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Producer", reflect.TypeOf((*MockSQS)(nil).Producer), ctx, ms)
}

// ReactivateMessage mocks base method.
func (m *MockSQS) ReactivateMessage(ch <-chan os.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReactivateMessage", ch)
}

// ReactivateMessage indicates an expected call of ReactivateMessage.
func (mr *MockSQSMockRecorder) ReactivateMessage(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReactivateMessage", reflect.TypeOf((*MockSQS)(nil).ReactivateMessage), ch)
}
