// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/grpc_response.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/grpc_response.go -destination=mocks/mock_grpc_response.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGrpcResponse is a mock of GrpcResponse interface.
type MockGrpcResponse struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcResponseMockRecorder
	isgomock struct{}
}

// MockGrpcResponseMockRecorder is the mock recorder for MockGrpcResponse.
type MockGrpcResponseMockRecorder struct {
	mock *MockGrpcResponse
}

// NewMockGrpcResponse creates a new mock instance.
func NewMockGrpcResponse(ctrl *gomock.Controller) *MockGrpcResponse {
	mock := &MockGrpcResponse{ctrl: ctrl}
	mock.recorder = &MockGrpcResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrpcResponse) EXPECT() *MockGrpcResponseMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockGrpcResponse) GetMessage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockGrpcResponseMockRecorder) GetMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockGrpcResponse)(nil).GetMessage))
}

// GetStatus mocks base method.
func (m *MockGrpcResponse) GetStatus() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockGrpcResponseMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockGrpcResponse)(nil).GetStatus))
}
