// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/stream_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/stream_client.go -destination=mocks/mock_stream_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	adapters "dominus-project/internal/domain/adapters"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamBi is a mock of StreamBi interface.
type MockStreamBi struct {
	ctrl     *gomock.Controller
	recorder *MockStreamBiMockRecorder
	isgomock struct{}
}

// MockStreamBiMockRecorder is the mock recorder for MockStreamBi.
type MockStreamBiMockRecorder struct {
	mock *MockStreamBi
}

// NewMockStreamBi creates a new mock instance.
func NewMockStreamBi(ctrl *gomock.Controller) *MockStreamBi {
	mock := &MockStreamBi{ctrl: ctrl}
	mock.recorder = &MockStreamBiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamBi) EXPECT() *MockStreamBiMockRecorder {
	return m.recorder
}

// Recv mocks base method.
func (m *MockStreamBi) Recv() (adapters.GrpcDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(adapters.GrpcDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStreamBiMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStreamBi)(nil).Recv))
}

// Send mocks base method.
func (m *MockStreamBi) Send(msg []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamBiMockRecorder) Send(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStreamBi)(nil).Send), msg)
}

// MockStreamClient is a mock of StreamClient interface.
type MockStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockStreamClientMockRecorder
	isgomock struct{}
}

// MockStreamClientMockRecorder is the mock recorder for MockStreamClient.
type MockStreamClientMockRecorder struct {
	mock *MockStreamClient
}

// NewMockStreamClient creates a new mock instance.
func NewMockStreamClient(ctrl *gomock.Controller) *MockStreamClient {
	mock := &MockStreamClient{ctrl: ctrl}
	mock.recorder = &MockStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamClient) EXPECT() *MockStreamClientMockRecorder {
	return m.recorder
}

// Recv mocks base method.
func (m *MockStreamClient) Recv() (adapters.GrpcDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(adapters.GrpcDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStreamClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStreamClient)(nil).Recv))
}
