// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\ack\dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\ack\dto.go -destination=.\mocks\mock_dto_ack.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAskDto is a mock of AskDto interface.
type MockAskDto struct {
	ctrl     *gomock.Controller
	recorder *MockAskDtoMockRecorder
	isgomock struct{}
}

// MockAskDtoMockRecorder is the mock recorder for MockAskDto.
type MockAskDtoMockRecorder struct {
	mock *MockAskDto
}

// NewMockAskDto creates a new mock instance.
func NewMockAskDto(ctrl *gomock.Controller) *MockAskDto {
	mock := &MockAskDto{ctrl: ctrl}
	mock.recorder = &MockAskDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAskDto) EXPECT() *MockAskDtoMockRecorder {
	return m.recorder
}

// GetGroupId mocks base method.
func (m *MockAskDto) GetGroupId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGroupId indicates an expected call of GetGroupId.
func (mr *MockAskDtoMockRecorder) GetGroupId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupId", reflect.TypeOf((*MockAskDto)(nil).GetGroupId))
}

// GetMessageId mocks base method.
func (m *MockAskDto) GetMessageId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMessageId indicates an expected call of GetMessageId.
func (mr *MockAskDtoMockRecorder) GetMessageId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageId", reflect.TypeOf((*MockAskDto)(nil).GetMessageId))
}

// GetWorkerId mocks base method.
func (m *MockAskDto) GetWorkerId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWorkerId indicates an expected call of GetWorkerId.
func (mr *MockAskDtoMockRecorder) GetWorkerId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerId", reflect.TypeOf((*MockAskDto)(nil).GetWorkerId))
}
