// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/entities/topic.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/entities/topic.go -destination=mocks/mock_topic.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTopic is a mock of Topic interface.
type MockTopic struct {
	ctrl     *gomock.Controller
	recorder *MockTopicMockRecorder
	isgomock struct{}
}

// MockTopicMockRecorder is the mock recorder for MockTopic.
type MockTopicMockRecorder struct {
	mock *MockTopic
}

// NewMockTopic creates a new mock instance.
func NewMockTopic(ctrl *gomock.Controller) *MockTopic {
	mock := &MockTopic{ctrl: ctrl}
	mock.recorder = &MockTopicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopic) EXPECT() *MockTopicMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockTopic) GetMessage() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockTopicMockRecorder) GetMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockTopic)(nil).GetMessage))
}

// GetName mocks base method.
func (m *MockTopic) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockTopicMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockTopic)(nil).GetName))
}

// GetSubscribers mocks base method.
func (m *MockTopic) GetSubscribers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockTopicMockRecorder) GetSubscribers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockTopic)(nil).GetSubscribers))
}

// ParseTopic mocks base method.
func (m *MockTopic) ParseTopic() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTopic")
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseTopic indicates an expected call of ParseTopic.
func (mr *MockTopicMockRecorder) ParseTopic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTopic", reflect.TypeOf((*MockTopic)(nil).ParseTopic))
}

// SetMessage mocks base method.
func (m *MockTopic) SetMessage(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessage", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessage indicates an expected call of SetMessage.
func (mr *MockTopicMockRecorder) SetMessage(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockTopic)(nil).SetMessage), data)
}

// SetName mocks base method.
func (m *MockTopic) SetName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetName", name)
}

// SetName indicates an expected call of SetName.
func (mr *MockTopicMockRecorder) SetName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockTopic)(nil).SetName), name)
}

// SetSubscribers mocks base method.
func (m *MockTopic) SetSubscribers(sb []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSubscribers", sb)
}

// SetSubscribers indicates an expected call of SetSubscribers.
func (mr *MockTopicMockRecorder) SetSubscribers(sb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscribers", reflect.TypeOf((*MockTopic)(nil).SetSubscribers), sb)
}

// ValidateTopic mocks base method.
func (m *MockTopic) ValidateTopic() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTopic")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTopic indicates an expected call of ValidateTopic.
func (mr *MockTopicMockRecorder) ValidateTopic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTopic", reflect.TypeOf((*MockTopic)(nil).ValidateTopic))
}

// MockparserBody is a mock of parserBody interface.
type MockparserBody struct {
	ctrl     *gomock.Controller
	recorder *MockparserBodyMockRecorder
	isgomock struct{}
}

// MockparserBodyMockRecorder is the mock recorder for MockparserBody.
type MockparserBodyMockRecorder struct {
	mock *MockparserBody
}

// NewMockparserBody creates a new mock instance.
func NewMockparserBody(ctrl *gomock.Controller) *MockparserBody {
	mock := &MockparserBody{ctrl: ctrl}
	mock.recorder = &MockparserBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparserBody) EXPECT() *MockparserBodyMockRecorder {
	return m.recorder
}

// BodyParser mocks base method.
func (m *MockparserBody) BodyParser(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyParser", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BodyParser indicates an expected call of BodyParser.
func (mr *MockparserBodyMockRecorder) BodyParser(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyParser", reflect.TypeOf((*MockparserBody)(nil).BodyParser), obj)
}
