// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/use_cases/broker/factory.go
//
// Generated by this command:
//
//	mockgen -source=./internal/application/use_cases/broker/factory.go -destination=./mocks/mock_usecase_broker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dtos "dominus-project/internal/application/dtos"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
	isgomock struct{}
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// StreamBiConn mocks base method.
func (m *MockBroker) StreamBiConn(st dtos.BrokerBidirectionalDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamBiConn", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamBiConn indicates an expected call of StreamBiConn.
func (mr *MockBrokerMockRecorder) StreamBiConn(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBiConn", reflect.TypeOf((*MockBroker)(nil).StreamBiConn), st)
}

// StreamClientConn mocks base method.
func (m *MockBroker) StreamClientConn(st dtos.BrokerClientDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamClientConn", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamClientConn indicates an expected call of StreamClientConn.
func (mr *MockBrokerMockRecorder) StreamClientConn(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamClientConn", reflect.TypeOf((*MockBroker)(nil).StreamClientConn), st)
}

// StreamServerConn mocks base method.
func (m *MockBroker) StreamServerConn(req dtos.BrokerRequestDto, st dtos.BrokerServerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamServerConn", req, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamServerConn indicates an expected call of StreamServerConn.
func (mr *MockBrokerMockRecorder) StreamServerConn(req, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamServerConn", reflect.TypeOf((*MockBroker)(nil).StreamServerConn), req, st)
}
