// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\stream_client\dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\stream_client\dto.go -destination=.\mocks\mock_dto_stream_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "dominus-broker/internal/application/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerClientDto is a mock of BrokerClientDto interface.
type MockBrokerClientDto struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerClientDtoMockRecorder
	isgomock struct{}
}

// MockBrokerClientDtoMockRecorder is the mock recorder for MockBrokerClientDto.
type MockBrokerClientDtoMockRecorder struct {
	mock *MockBrokerClientDto
}

// NewMockBrokerClientDto creates a new mock instance.
func NewMockBrokerClientDto(ctrl *gomock.Controller) *MockBrokerClientDto {
	mock := &MockBrokerClientDto{ctrl: ctrl}
	mock.recorder = &MockBrokerClientDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerClientDto) EXPECT() *MockBrokerClientDtoMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockBrokerClientDto) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBrokerClientDtoMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBrokerClientDto)(nil).Context))
}

// Recv mocks base method.
func (m *MockBrokerClientDto) Recv() (dto.BrokerRequestDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(dto.BrokerRequestDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockBrokerClientDtoMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockBrokerClientDto)(nil).Recv))
}
