// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/services/memory.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/services/memory.go -destination=./mocks/mock_services_memory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemory is a mock of Memory interface.
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
	isgomock struct{}
}

// MockMemoryMockRecorder is the mock recorder for MockMemory.
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance.
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// CheckMemory mocks base method.
func (m *MockMemory) CheckMemory() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMemory")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckMemory indicates an expected call of CheckMemory.
func (mr *MockMemoryMockRecorder) CheckMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMemory", reflect.TypeOf((*MockMemory)(nil).CheckMemory))
}

// Delete mocks base method.
func (m *MockMemory) Delete(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", id)
}

// Delete indicates an expected call of Delete.
func (mr *MockMemoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemory)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockMemory) Find(id string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockMemoryMockRecorder) Find(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMemory)(nil).Find), id)
}

// Iter mocks base method.
func (m *MockMemory) Iter(pos int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iter", pos)
	ret0, _ := ret[0].(string)
	return ret0
}

// Iter indicates an expected call of Iter.
func (mr *MockMemoryMockRecorder) Iter(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iter", reflect.TypeOf((*MockMemory)(nil).Iter), pos)
}

// Len mocks base method.
func (m *MockMemory) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockMemoryMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockMemory)(nil).Len))
}

// Set mocks base method.
func (m *MockMemory) Set(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", id)
}

// Set indicates an expected call of Set.
func (mr *MockMemoryMockRecorder) Set(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMemory)(nil).Set), id)
}
