// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\producer\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\producer\factory.go -destination=.\mocks\mock_usecases_producer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	producer "dominus-broker/internal/application/usecases/producer"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerUseCase is a mock of ProducerUseCase interface.
type MockProducerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProducerUseCaseMockRecorder
	isgomock struct{}
}

// MockProducerUseCaseMockRecorder is the mock recorder for MockProducerUseCase.
type MockProducerUseCaseMockRecorder struct {
	mock *MockProducerUseCase
}

// NewMockProducerUseCase creates a new mock instance.
func NewMockProducerUseCase(ctrl *gomock.Controller) *MockProducerUseCase {
	mock := &MockProducerUseCase{ctrl: ctrl}
	mock.recorder = &MockProducerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerUseCase) EXPECT() *MockProducerUseCaseMockRecorder {
	return m.recorder
}

// Producer mocks base method.
func (m *MockProducerUseCase) Producer(ctx context.Context, ms producer.ProducerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Producer", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Producer indicates an expected call of Producer.
func (mr *MockProducerUseCaseMockRecorder) Producer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Producer", reflect.TypeOf((*MockProducerUseCase)(nil).Producer), ctx, ms)
}
