// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\domain\repositories\sqs.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\domain\repositories\sqs.go -destination=.\mocks\mock_repositories_sqs.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "dominus-broker/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemoryClient is a mock of MemoryClient interface.
type MockMemoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryClientMockRecorder
	isgomock struct{}
}

// MockMemoryClientMockRecorder is the mock recorder for MockMemoryClient.
type MockMemoryClientMockRecorder struct {
	mock *MockMemoryClient
}

// NewMockMemoryClient creates a new mock instance.
func NewMockMemoryClient(ctrl *gomock.Controller) *MockMemoryClient {
	mock := &MockMemoryClient{ctrl: ctrl}
	mock.recorder = &MockMemoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryClient) EXPECT() *MockMemoryClientMockRecorder {
	return m.recorder
}

// AckMessage mocks base method.
func (m *MockMemoryClient) AckMessage(ctx context.Context, messageId, groupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckMessage", ctx, messageId, groupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AckMessage indicates an expected call of AckMessage.
func (mr *MockMemoryClientMockRecorder) AckMessage(ctx, messageId, groupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckMessage", reflect.TypeOf((*MockMemoryClient)(nil).AckMessage), ctx, messageId, groupId)
}

// GetMessage mocks base method.
func (m *MockMemoryClient) GetMessage(ctx context.Context, workerId, groupId string) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, workerId, groupId)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMemoryClientMockRecorder) GetMessage(ctx, workerId, groupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMemoryClient)(nil).GetMessage), ctx, workerId, groupId)
}

// Group mocks base method.
func (m *MockMemoryClient) Group(groupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", groupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Group indicates an expected call of Group.
func (mr *MockMemoryClientMockRecorder) Group(groupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockMemoryClient)(nil).Group), groupId)
}

// SendMessage mocks base method.
func (m *MockMemoryClient) SendMessage(ctx context.Context, q *entities.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, q)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMemoryClientMockRecorder) SendMessage(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMemoryClient)(nil).SendMessage), ctx, q)
}

// MockCheckerClient is a mock of CheckerClient interface.
type MockCheckerClient struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerClientMockRecorder
	isgomock struct{}
}

// MockCheckerClientMockRecorder is the mock recorder for MockCheckerClient.
type MockCheckerClientMockRecorder struct {
	mock *MockCheckerClient
}

// NewMockCheckerClient creates a new mock instance.
func NewMockCheckerClient(ctrl *gomock.Controller) *MockCheckerClient {
	mock := &MockCheckerClient{ctrl: ctrl}
	mock.recorder = &MockCheckerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckerClient) EXPECT() *MockCheckerClientMockRecorder {
	return m.recorder
}

// CheckConsumer mocks base method.
func (m *MockCheckerClient) CheckConsumer(ctx context.Context, key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConsumer", ctx, key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckConsumer indicates an expected call of CheckConsumer.
func (mr *MockCheckerClientMockRecorder) CheckConsumer(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConsumer", reflect.TypeOf((*MockCheckerClient)(nil).CheckConsumer), ctx, key)
}

// SaveConsumer mocks base method.
func (m *MockCheckerClient) SaveConsumer(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConsumer", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConsumer indicates an expected call of SaveConsumer.
func (mr *MockCheckerClientMockRecorder) SaveConsumer(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConsumer", reflect.TypeOf((*MockCheckerClient)(nil).SaveConsumer), ctx, key)
}
