// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/adapters/rest_dto.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/adapters/rest_dto.go -destination=mocks/mock_rest_dto.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRestDto is a mock of RestDto interface.
type MockRestDto struct {
	ctrl     *gomock.Controller
	recorder *MockRestDtoMockRecorder
	isgomock struct{}
}

// MockRestDtoMockRecorder is the mock recorder for MockRestDto.
type MockRestDtoMockRecorder struct {
	mock *MockRestDto
}

// NewMockRestDto creates a new mock instance.
func NewMockRestDto(ctrl *gomock.Controller) *MockRestDto {
	mock := &MockRestDto{ctrl: ctrl}
	mock.recorder = &MockRestDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestDto) EXPECT() *MockRestDtoMockRecorder {
	return m.recorder
}

// BodyParser mocks base method.
func (m *MockRestDto) BodyParser(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyParser", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BodyParser indicates an expected call of BodyParser.
func (mr *MockRestDtoMockRecorder) BodyParser(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyParser", reflect.TypeOf((*MockRestDto)(nil).BodyParser), obj)
}

// Param mocks base method.
func (m *MockRestDto) Param(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Param", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// Param indicates an expected call of Param.
func (mr *MockRestDtoMockRecorder) Param(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Param", reflect.TypeOf((*MockRestDto)(nil).Param), key)
}
