// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\producer\dto.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\producer\dto.go -destination=.\mocks\mock_dto_producer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerDto is a mock of ProducerDto interface.
type MockProducerDto struct {
	ctrl     *gomock.Controller
	recorder *MockProducerDtoMockRecorder
	isgomock struct{}
}

// MockProducerDtoMockRecorder is the mock recorder for MockProducerDto.
type MockProducerDtoMockRecorder struct {
	mock *MockProducerDto
}

// NewMockProducerDto creates a new mock instance.
func NewMockProducerDto(ctrl *gomock.Controller) *MockProducerDto {
	mock := &MockProducerDto{ctrl: ctrl}
	mock.recorder = &MockProducerDtoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerDto) EXPECT() *MockProducerDtoMockRecorder {
	return m.recorder
}

// GetPayload mocks base method.
func (m *MockProducerDto) GetPayload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockProducerDtoMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockProducerDto)(nil).GetPayload))
}
