// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/use_cases/queue/factory.go
//
// Generated by this command:
//
//	mockgen -source=./internal/application/use_cases/queue/factory.go -destination=./mocks/mock_usecase_queue.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dtos "dominus-project/internal/application/dtos"
	entities "dominus-project/internal/domain/entities"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// CheckMemory mocks base method.
func (m *MockQueue) CheckMemory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckMemory")
}

// CheckMemory indicates an expected call of CheckMemory.
func (mr *MockQueueMockRecorder) CheckMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMemory", reflect.TypeOf((*MockQueue)(nil).CheckMemory))
}

// Consumer mocks base method.
func (m *MockQueue) Consumer(ctx context.Context) (*entities.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumer", ctx)
	ret0, _ := ret[0].(*entities.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consumer indicates an expected call of Consumer.
func (mr *MockQueueMockRecorder) Consumer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumer", reflect.TypeOf((*MockQueue)(nil).Consumer), ctx)
}

// ConsumerDLT mocks base method.
func (m *MockQueue) ConsumerDLT(ctx context.Context, ms dtos.ConsumerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerDLT", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumerDLT indicates an expected call of ConsumerDLT.
func (mr *MockQueueMockRecorder) ConsumerDLT(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerDLT", reflect.TypeOf((*MockQueue)(nil).ConsumerDLT), ctx, ms)
}

// Producer mocks base method.
func (m *MockQueue) Producer(ctx context.Context, ms dtos.ProducerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Producer", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Producer indicates an expected call of Producer.
func (mr *MockQueueMockRecorder) Producer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Producer", reflect.TypeOf((*MockQueue)(nil).Producer), ctx, ms)
}

// ReactivateMessage mocks base method.
func (m *MockQueue) ReactivateMessage(ch <-chan os.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReactivateMessage", ch)
}

// ReactivateMessage indicates an expected call of ReactivateMessage.
func (mr *MockQueueMockRecorder) ReactivateMessage(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReactivateMessage", reflect.TypeOf((*MockQueue)(nil).ReactivateMessage), ch)
}
