// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interactors/manager/factory.go
//
// Generated by this command:
//
//	mockgen -source=internal/interactors/manager/factory.go -destination=mocks/mock_manager_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	adapters "dominus-project/internal/domain/adapters"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManagerService is a mock of ManagerService interface.
type MockManagerService struct {
	ctrl     *gomock.Controller
	recorder *MockManagerServiceMockRecorder
	isgomock struct{}
}

// MockManagerServiceMockRecorder is the mock recorder for MockManagerService.
type MockManagerServiceMockRecorder struct {
	mock *MockManagerService
}

// NewMockManagerService creates a new mock instance.
func NewMockManagerService(ctrl *gomock.Controller) *MockManagerService {
	mock := &MockManagerService{ctrl: ctrl}
	mock.recorder = &MockManagerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagerService) EXPECT() *MockManagerServiceMockRecorder {
	return m.recorder
}

// AddTopic mocks base method.
func (m *MockManagerService) AddTopic(ctx adapters.RestDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTopic", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTopic indicates an expected call of AddTopic.
func (mr *MockManagerServiceMockRecorder) AddTopic(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTopic", reflect.TypeOf((*MockManagerService)(nil).AddTopic), ctx)
}

// DeleteTopic mocks base method.
func (m *MockManagerService) DeleteTopic(ctx adapters.RestDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockManagerServiceMockRecorder) DeleteTopic(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockManagerService)(nil).DeleteTopic), ctx)
}

// GetQueueInfo mocks base method.
func (m *MockManagerService) GetQueueInfo() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueInfo")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetQueueInfo indicates an expected call of GetQueueInfo.
func (mr *MockManagerServiceMockRecorder) GetQueueInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueInfo", reflect.TypeOf((*MockManagerService)(nil).GetQueueInfo))
}

// UpdateSubscribers mocks base method.
func (m *MockManagerService) UpdateSubscribers(ctx adapters.RestDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscribers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscribers indicates an expected call of UpdateSubscribers.
func (mr *MockManagerServiceMockRecorder) UpdateSubscribers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscribers", reflect.TypeOf((*MockManagerService)(nil).UpdateSubscribers), ctx)
}
