// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/entities/topics.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/entities/topics.go -destination=mocks/mock_topics.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "dominus-project/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTopics is a mock of Topics interface.
type MockTopics struct {
	ctrl     *gomock.Controller
	recorder *MockTopicsMockRecorder
	isgomock struct{}
}

// MockTopicsMockRecorder is the mock recorder for MockTopics.
type MockTopicsMockRecorder struct {
	mock *MockTopics
}

// NewMockTopics creates a new mock instance.
func NewMockTopics(ctrl *gomock.Controller) *MockTopics {
	mock := &MockTopics{ctrl: ctrl}
	mock.recorder = &MockTopicsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopics) EXPECT() *MockTopicsMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockTopics) Append(t entities.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockTopicsMockRecorder) Append(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockTopics)(nil).Append), t)
}

// Delete mocks base method.
func (m *MockTopics) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTopicsMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTopics)(nil).Delete), name)
}

// Find mocks base method.
func (m *MockTopics) Find(topic string) (entities.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", topic)
	ret0, _ := ret[0].(entities.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTopicsMockRecorder) Find(topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTopics)(nil).Find), topic)
}

// GetTopicsInfo mocks base method.
func (m *MockTopics) GetTopicsInfo() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsInfo")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetTopicsInfo indicates an expected call of GetTopicsInfo.
func (mr *MockTopicsMockRecorder) GetTopicsInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsInfo", reflect.TypeOf((*MockTopics)(nil).GetTopicsInfo))
}

// Next mocks base method.
func (m *MockTopics) Next() (entities.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(entities.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockTopicsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockTopics)(nil).Next))
}

// Update mocks base method.
func (m *MockTopics) Update(t entities.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTopicsMockRecorder) Update(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTopics)(nil).Update), t)
}
