// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\application\usecases\sqs\factory.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\application\usecases\sqs\factory.go -destination=.\mocks\mock_usecases_sqs.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sqs "dominus-broker/internal/application/usecases/sqs"
	entities "dominus-broker/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSqs is a mock of Sqs interface.
type MockSqs struct {
	ctrl     *gomock.Controller
	recorder *MockSqsMockRecorder
	isgomock struct{}
}

// MockSqsMockRecorder is the mock recorder for MockSqs.
type MockSqsMockRecorder struct {
	mock *MockSqs
}

// NewMockSqs creates a new mock instance.
func NewMockSqs(ctrl *gomock.Controller) *MockSqs {
	mock := &MockSqs{ctrl: ctrl}
	mock.recorder = &MockSqsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqs) EXPECT() *MockSqsMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockSqs) Ack(ctx context.Context, ms sqs.ConsumerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockSqsMockRecorder) Ack(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockSqs)(nil).Ack), ctx, ms)
}

// Consumer mocks base method.
func (m *MockSqs) Consumer(ctx context.Context, ms sqs.ConsumerDto) (*entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumer", ctx, ms)
	ret0, _ := ret[0].(*entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consumer indicates an expected call of Consumer.
func (mr *MockSqsMockRecorder) Consumer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumer", reflect.TypeOf((*MockSqs)(nil).Consumer), ctx, ms)
}

// Producer mocks base method.
func (m *MockSqs) Producer(ctx context.Context, ms sqs.ProducerDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Producer", ctx, ms)
	ret0, _ := ret[0].(error)
	return ret0
}

// Producer indicates an expected call of Producer.
func (mr *MockSqsMockRecorder) Producer(ctx, ms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Producer", reflect.TypeOf((*MockSqs)(nil).Producer), ctx, ms)
}
