// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: grpc.proto

package builder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Grpc_Simple_FullMethodName              = "/builder.Grpc/Simple"
	Grpc_ClientStream_FullMethodName        = "/builder.Grpc/ClientStream"
	Grpc_ServerStream_FullMethodName        = "/builder.Grpc/ServerStream"
	Grpc_BidirectionalStream_FullMethodName = "/builder.Grpc/BidirectionalStream"
)

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcClient interface {
	Simple(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (Grpc_ClientStreamClient, error)
	ServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (Grpc_ServerStreamClient, error)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (Grpc_BidirectionalStreamClient, error)
}

type grpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcClient(cc grpc.ClientConnInterface) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Simple(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Grpc_Simple_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (Grpc_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[0], Grpc_ClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcClientStreamClient{stream}
	return x, nil
}

type Grpc_ClientStreamClient interface {
	Send(*RequestMessage) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type grpcClientStreamClient struct {
	grpc.ClientStream
}

func (x *grpcClientStreamClient) Send(m *RequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcClientStreamClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcClient) ServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (Grpc_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[1], Grpc_ServerStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Grpc_ServerStreamClient interface {
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type grpcServerStreamClient struct {
	grpc.ClientStream
}

func (x *grpcServerStreamClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (Grpc_BidirectionalStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[2], Grpc_BidirectionalStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcBidirectionalStreamClient{stream}
	return x, nil
}

type Grpc_BidirectionalStreamClient interface {
	Send(*RequestMessage) error
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type grpcBidirectionalStreamClient struct {
	grpc.ClientStream
}

func (x *grpcBidirectionalStreamClient) Send(m *RequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcBidirectionalStreamClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcServer is the server API for Grpc service.
// All implementations must embed UnimplementedGrpcServer
// for forward compatibility
type GrpcServer interface {
	Simple(context.Context, *RequestMessage) (*Response, error)
	ClientStream(Grpc_ClientStreamServer) error
	ServerStream(*RequestMessage, Grpc_ServerStreamServer) error
	BidirectionalStream(Grpc_BidirectionalStreamServer) error
	mustEmbedUnimplementedGrpcServer()
}

// UnimplementedGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcServer struct {
}

func (UnimplementedGrpcServer) Simple(context.Context, *RequestMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
}
func (UnimplementedGrpcServer) ClientStream(Grpc_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedGrpcServer) ServerStream(*RequestMessage, Grpc_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedGrpcServer) BidirectionalStream(Grpc_BidirectionalStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedGrpcServer) mustEmbedUnimplementedGrpcServer() {}

// UnsafeGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServer will
// result in compilation errors.
type UnsafeGrpcServer interface {
	mustEmbedUnimplementedGrpcServer()
}

func RegisterGrpcServer(s grpc.ServiceRegistrar, srv GrpcServer) {
	s.RegisterService(&Grpc_ServiceDesc, srv)
}

func _Grpc_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grpc_Simple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Simple(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).ClientStream(&grpcClientStreamServer{stream})
}

type Grpc_ClientStreamServer interface {
	SendAndClose(*Response) error
	Recv() (*RequestMessage, error)
	grpc.ServerStream
}

type grpcClientStreamServer struct {
	grpc.ServerStream
}

func (x *grpcClientStreamServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcClientStreamServer) Recv() (*RequestMessage, error) {
	m := new(RequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Grpc_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcServer).ServerStream(m, &grpcServerStreamServer{stream})
}

type Grpc_ServerStreamServer interface {
	Send(*ResponseMessage) error
	grpc.ServerStream
}

type grpcServerStreamServer struct {
	grpc.ServerStream
}

func (x *grpcServerStreamServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Grpc_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).BidirectionalStream(&grpcBidirectionalStreamServer{stream})
}

type Grpc_BidirectionalStreamServer interface {
	Send(*ResponseMessage) error
	Recv() (*RequestMessage, error)
	grpc.ServerStream
}

type grpcBidirectionalStreamServer struct {
	grpc.ServerStream
}

func (x *grpcBidirectionalStreamServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcBidirectionalStreamServer) Recv() (*RequestMessage, error) {
	m := new(RequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Grpc_ServiceDesc is the grpc.ServiceDesc for Grpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Grpc_Simple_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _Grpc_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStream",
			Handler:       _Grpc_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _Grpc_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
