syntax = "proto3";

package builder;

import "validate.proto";

option go_package = "dominus/app/interfaces/grpc/proto/builder";


//Message
message RequestMessage {
    string topic = 1 [(validate.rules).string.max_len = 20];
    bytes payload = 2 [(validate.rules).bytes = {
        min_len: 1,          
        max_len: 65535         
    }];
}

message ResponseMessage {
    bytes payload = 1 [(validate.rules).bytes = {
        min_len: 1,          
        max_len: 65535         
    }];
}


//Response
message Response {
    uint32  status = 1;
    string  message = 2;
}


//Services
service API {
    rpc Send(RequestMessage) returns (Response);
    rpc SendClientStream(stream RequestMessage) returns (Response);
    rpc SendServerStream(RequestMessage) returns (stream ResponseMessage);
    rpc SendFullDuplexStream(stream RequestMessage) returns (stream ResponseMessage);
}