syntax = "proto3";

package builder;

import "validate.proto";

option go_package = "dominus/app/interfaces/grpc/proto/builder";


//Message
message Message {
    string topic = 1 [(validate.rules).string.max_len = 20];
    bytes payload = 2 [(validate.rules).bytes = {
        min_len: 1,          
        max_len: 65535         
    }];
}


//Response
message Response {
    uint32  status = 1;
    string  message = 2;
}


//Services
service API {
    rpc SendRemote(Message) returns (Response);
    rpc SendClientStreamRemote(stream Message) returns (Response);
    rpc SendServerStreamRemote(Message) returns (stream Message);
    rpc SendStreamRemote(stream Message) returns (stream Message);

    rpc SendLocal(Message) returns (Response);
    rpc SendClientStreamLocal(stream Message) returns (Response);
    rpc SendServerStreamLocal(Message) returns (stream Message);
    rpc SendStreamLocal(stream Message) returns (stream Message);
}