// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: validate.proto

package validate

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FieldRules with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FieldRules) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FieldRules with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FieldRulesMultiError, or
// nil if none found.
func (m *FieldRules) ValidateAll() error {
	return m.validate(true)
}

func (m *FieldRules) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Type.(type) {
	case *FieldRules_String_:
		if v == nil {
			err := FieldRulesValidationError{
				field:  "Type",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetString_()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FieldRulesValidationError{
						field:  "String_",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FieldRulesValidationError{
						field:  "String_",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetString_()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FieldRulesValidationError{
					field:  "String_",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *FieldRules_Bytes:
		if v == nil {
			err := FieldRulesValidationError{
				field:  "Type",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBytes()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FieldRulesValidationError{
						field:  "Bytes",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FieldRulesValidationError{
						field:  "Bytes",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBytes()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FieldRulesValidationError{
					field:  "Bytes",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return FieldRulesMultiError(errors)
	}

	return nil
}

// FieldRulesMultiError is an error wrapping multiple validation errors
// returned by FieldRules.ValidateAll() if the designated constraints aren't met.
type FieldRulesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FieldRulesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FieldRulesMultiError) AllErrors() []error { return m }

// FieldRulesValidationError is the validation error returned by
// FieldRules.Validate if the designated constraints aren't met.
type FieldRulesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldRulesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldRulesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldRulesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldRulesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldRulesValidationError) ErrorName() string { return "FieldRulesValidationError" }

// Error satisfies the builtin error interface
func (e FieldRulesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldRules.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldRulesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldRulesValidationError{}

// Validate checks the field values on StringRules with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StringRules) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StringRules with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StringRulesMultiError, or
// nil if none found.
func (m *StringRules) ValidateAll() error {
	return m.validate(true)
}

func (m *StringRules) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Const

	// no validation rules for Len

	// no validation rules for MinLen

	// no validation rules for MaxLen

	// no validation rules for LenBytes

	// no validation rules for MinBytes

	// no validation rules for MaxBytes

	// no validation rules for Pattern

	// no validation rules for Prefix

	// no validation rules for Suffix

	// no validation rules for Contains

	// no validation rules for NotContains

	// no validation rules for Strict

	// no validation rules for IgnoreEmpty

	switch v := m.WellKnown.(type) {
	case *StringRules_Email:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Email
	case *StringRules_Hostname:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Hostname
	case *StringRules_Ip:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ip
	case *StringRules_Ipv4:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ipv4
	case *StringRules_Ipv6:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ipv6
	case *StringRules_Uri:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Uri
	case *StringRules_UriRef:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for UriRef
	case *StringRules_Address:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Address
	case *StringRules_Uuid:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Uuid
	case *StringRules_WellKnownRegex:
		if v == nil {
			err := StringRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for WellKnownRegex
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return StringRulesMultiError(errors)
	}

	return nil
}

// StringRulesMultiError is an error wrapping multiple validation errors
// returned by StringRules.ValidateAll() if the designated constraints aren't met.
type StringRulesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StringRulesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StringRulesMultiError) AllErrors() []error { return m }

// StringRulesValidationError is the validation error returned by
// StringRules.Validate if the designated constraints aren't met.
type StringRulesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StringRulesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StringRulesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StringRulesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StringRulesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StringRulesValidationError) ErrorName() string { return "StringRulesValidationError" }

// Error satisfies the builtin error interface
func (e StringRulesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStringRules.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StringRulesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StringRulesValidationError{}

// Validate checks the field values on BytesRules with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BytesRules) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BytesRules with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BytesRulesMultiError, or
// nil if none found.
func (m *BytesRules) ValidateAll() error {
	return m.validate(true)
}

func (m *BytesRules) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Const

	// no validation rules for Len

	// no validation rules for MinLen

	// no validation rules for MaxLen

	// no validation rules for Pattern

	// no validation rules for Prefix

	// no validation rules for Suffix

	// no validation rules for Contains

	// no validation rules for IgnoreEmpty

	switch v := m.WellKnown.(type) {
	case *BytesRules_Ip:
		if v == nil {
			err := BytesRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ip
	case *BytesRules_Ipv4:
		if v == nil {
			err := BytesRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ipv4
	case *BytesRules_Ipv6:
		if v == nil {
			err := BytesRulesValidationError{
				field:  "WellKnown",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Ipv6
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return BytesRulesMultiError(errors)
	}

	return nil
}

// BytesRulesMultiError is an error wrapping multiple validation errors
// returned by BytesRules.ValidateAll() if the designated constraints aren't met.
type BytesRulesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BytesRulesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BytesRulesMultiError) AllErrors() []error { return m }

// BytesRulesValidationError is the validation error returned by
// BytesRules.Validate if the designated constraints aren't met.
type BytesRulesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BytesRulesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BytesRulesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BytesRulesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BytesRulesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BytesRulesValidationError) ErrorName() string { return "BytesRulesValidationError" }

// Error satisfies the builtin error interface
func (e BytesRulesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBytesRules.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BytesRulesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BytesRulesValidationError{}
