package enum

const (
	INFO                       = "info"
	DEBUG                      = "debug"
	WARN                       = "warn"
	ID                         = "id"
	ERROR                      = "error"
	LOGCLIENT                  = "logclient"
	X_API_KEY                  = "x-api-key"
	DESCRIPTION_DELETE_MESSAGE = "message deleted successful"
	INVALID_PAYLOAD            = "invalid payload"
	INVALID_ID                 = "invalid message id"
	DEBUG_DESCRIPTION          = "system debuging activated"
	SUBCRIBER_NOT_FOUND        = "subscirbers not found"
	REQUEST_OK                 = "request accepted"
	NOT_FOUND                  = "not found"
	MATCH_TOKEN                = "failed to match token"
	NO_HOST_ALLOW              = "host not allowed"
	ALL_KEYS                   = "*"
	EMPTY_STRING               = ""
	DOMAIN                     = "dominus.com"
	ROUTER_CLIENT              = `{"loadBalancingConfig":[{"round_robin":{}}]}`
	PROJECT_NAME               = "Dominus"
	IDEM_POTENCY_HEADER        = "idempotency-header"
	IDEM_POTENCY_TAG           = "idempotency"
	CONTENT_TYPE_TEXT          = "application/text"
	PAYLOAD                    = "payload"
	START_FROM_NEW_MESSAGE     = "$"
	GROUP_ID                   = "empty group id"
	WORKER_ID                  = "empty worker id"
	IDEM_POTENCY_NOT_FOUND     = "idempotency not found"
	RATE_LIMIT_REACHED         = "rate limit reached"
)
