info:
  contact:
    email: ingmbi8807@gmail.com
    name: MBI
    url: https://www.pr0c0d3.com/
  description: <h3>This server is a bidirectional queue using gRCP. Manager section</h3>
  title: Dominus server
  version: 1.0.0
paths:
  /logs:
    get:
      description: <h3>gets all logs fron the database using page and size (required)</h3>
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: size
        in: query
        name: size
        required: true
        type: integer
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Manager
  /logs-backup:
    get:
      description: <h3>Gets all selected items from the database for making a backup</h3>
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: Error response
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      tags:
      - Manager
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: API_TOKEN
    type: apiKey
swagger: "2.0"
