basePath: /
definitions:
  entities.Logs:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      stage:
        type: string
      subscriber:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: ingmbi8807@gmail.com
    name: MBI
    url: https://www.pr0c0d3.com/
  description: <h3>This server is a bidirectional queue using gRCP. Manager section</h3>
  title: Dominus server
  version: 1.0.0
paths:
  /manager:
    delete:
      description: delete all logs in the database
      parameters:
      - description: api token to connect with Dominus
        in: header
        name: API_TOKEN
        required: true
        type: string
      responses:
        "200":
          description: Respose body {message:string}
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: delete logs
      tags:
      - Manager
    get:
      description: gets all logs fron the database using page and size (required)
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: size
        in: query
        name: size
        required: true
        type: integer
      - description: api token to connect with Dominus
        in: header
        name: API_TOKEN
        required: true
        type: string
      responses:
        "200":
          description: Respose body {id:string,desc:string,create_at:time, stage:string,
            subscriber:string}
          schema:
            $ref: '#/definitions/entities.Logs'
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: gets logs
      tags:
      - Manager
  /manager-backup:
    get:
      description: gets all selected items from the database for making a backup
      parameters:
      - description: api token to connect with Dominus
        in: header
        name: API_TOKEN
        required: true
        type: string
      responses:
        "200":
          description: Respose body {logs:[{id:string,desc:string,create_at:time,
            stage:string, subscriber:string}]}
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: gets backup
      tags:
      - Manager
  /manager-pages:
    get:
      description: gets total pages in the database
      parameters:
      - description: api token to connect with Dominus
        in: header
        name: API_TOKEN
        required: true
        type: string
      responses:
        "200":
          description: Respose body {pages:int}
          schema:
            additionalProperties:
              type: integer
            type: object
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: gets pages
      tags:
      - Manager
  /manager-stats:
    get:
      description: gets all statistic from the database
      parameters:
      - description: api token to connect with Dominus
        in: header
        name: API_TOKEN
        required: true
        type: string
      responses:
        "200":
          description: 'Respose body { avgObjSize: int,collections: int, dataSize:
            int, db: string, fsTotalSize: int, fsUsedSize: int, indexSize: int, indexes:
            int, objects: int,ok: int, scaleFactor: int, storageSize: int, totalSize:
            int, views: int}'
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 'Response body {message: error}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: gets stats
      tags:
      - Manager
swagger: "2.0"
