syntax = "proto3";

package dominus;

option go_package = "dominus/app/interfaces/grpc/proto/dominus";


//Message
message RequestMessage {
    repeated string subscribers = 1;
    bytes payload = 2;
}

message ResponseMessage {
    bytes payload = 1;
}


//Response
message Response {
    int64  status = 1;
    string  message = 2;
}


//Services
service Grpc {
    rpc Simple(RequestMessage) returns (Response);
    rpc ClientStream(stream RequestMessage) returns (Response);
    rpc ServerStream(RequestMessage) returns (stream ResponseMessage);
    rpc BidirectionalStream(stream RequestMessage) returns (stream ResponseMessage);
}