// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dominus.proto

package dominus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grpc_Simple_FullMethodName              = "/dominus.Grpc/Simple"
	Grpc_ClientStream_FullMethodName        = "/dominus.Grpc/ClientStream"
	Grpc_ServerStream_FullMethodName        = "/dominus.Grpc/ServerStream"
	Grpc_BidirectionalStream_FullMethodName = "/dominus.Grpc/BidirectionalStream"
)

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Services
type GrpcClient interface {
	Simple(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestMessage, Response], error)
	ServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseMessage], error)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ResponseMessage], error)
}

type grpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcClient(cc grpc.ClientConnInterface) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Simple(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Grpc_Simple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestMessage, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[0], Grpc_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestMessage, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_ClientStreamClient = grpc.ClientStreamingClient[RequestMessage, Response]

func (c *grpcClient) ServerStream(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[1], Grpc_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestMessage, ResponseMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_ServerStreamClient = grpc.ServerStreamingClient[ResponseMessage]

func (c *grpcClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestMessage, ResponseMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[2], Grpc_BidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestMessage, ResponseMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_BidirectionalStreamClient = grpc.BidiStreamingClient[RequestMessage, ResponseMessage]

// GrpcServer is the server API for Grpc service.
// All implementations must embed UnimplementedGrpcServer
// for forward compatibility.
//
// Services
type GrpcServer interface {
	Simple(context.Context, *RequestMessage) (*Response, error)
	ClientStream(grpc.ClientStreamingServer[RequestMessage, Response]) error
	ServerStream(*RequestMessage, grpc.ServerStreamingServer[ResponseMessage]) error
	BidirectionalStream(grpc.BidiStreamingServer[RequestMessage, ResponseMessage]) error
	mustEmbedUnimplementedGrpcServer()
}

// UnimplementedGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcServer struct{}

func (UnimplementedGrpcServer) Simple(context.Context, *RequestMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
}
func (UnimplementedGrpcServer) ClientStream(grpc.ClientStreamingServer[RequestMessage, Response]) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedGrpcServer) ServerStream(*RequestMessage, grpc.ServerStreamingServer[ResponseMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedGrpcServer) BidirectionalStream(grpc.BidiStreamingServer[RequestMessage, ResponseMessage]) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedGrpcServer) mustEmbedUnimplementedGrpcServer() {}
func (UnimplementedGrpcServer) testEmbeddedByValue()              {}

// UnsafeGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServer will
// result in compilation errors.
type UnsafeGrpcServer interface {
	mustEmbedUnimplementedGrpcServer()
}

func RegisterGrpcServer(s grpc.ServiceRegistrar, srv GrpcServer) {
	// If the following call pancis, it indicates UnimplementedGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grpc_ServiceDesc, srv)
}

func _Grpc_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grpc_Simple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Simple(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).ClientStream(&grpc.GenericServerStream[RequestMessage, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_ClientStreamServer = grpc.ClientStreamingServer[RequestMessage, Response]

func _Grpc_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcServer).ServerStream(m, &grpc.GenericServerStream[RequestMessage, ResponseMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_ServerStreamServer = grpc.ServerStreamingServer[ResponseMessage]

func _Grpc_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).BidirectionalStream(&grpc.GenericServerStream[RequestMessage, ResponseMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_BidirectionalStreamServer = grpc.BidiStreamingServer[RequestMessage, ResponseMessage]

// Grpc_ServiceDesc is the grpc.ServiceDesc for Grpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dominus.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Grpc_Simple_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _Grpc_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStream",
			Handler:       _Grpc_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _Grpc_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dominus.proto",
}
