// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: dominus.proto

package dominus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Message
type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribers   []string               `protobuf:"bytes,1,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_dominus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dominus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_dominus_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetSubscribers() []string {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

func (x *RequestMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_dominus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dominus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_dominus_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

//Response
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_dominus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_dominus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_dominus_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dominus_proto protoreflect.FileDescriptor

const file_dominus_proto_rawDesc = "" +
	"\n" +
	"\rdominus.proto\x12\adominus\"L\n" +
	"\x0eRequestMessage\x12 \n" +
	"\vsubscribers\x18\x01 \x03(\tR\vsubscribers\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"+\n" +
	"\x0fResponseMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"<\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8d\x02\n" +
	"\x04Grpc\x124\n" +
	"\x06Simple\x12\x17.dominus.RequestMessage\x1a\x11.dominus.Response\x12<\n" +
	"\fClientStream\x12\x17.dominus.RequestMessage\x1a\x11.dominus.Response(\x01\x12C\n" +
	"\fServerStream\x12\x17.dominus.RequestMessage\x1a\x18.dominus.ResponseMessage0\x01\x12L\n" +
	"\x13BidirectionalStream\x12\x17.dominus.RequestMessage\x1a\x18.dominus.ResponseMessage(\x010\x01B+Z)dominus/app/interfaces/grpc/proto/dominusb\x06proto3"

var (
	file_dominus_proto_rawDescOnce sync.Once
	file_dominus_proto_rawDescData []byte
)

func file_dominus_proto_rawDescGZIP() []byte {
	file_dominus_proto_rawDescOnce.Do(func() {
		file_dominus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dominus_proto_rawDesc), len(file_dominus_proto_rawDesc)))
	})
	return file_dominus_proto_rawDescData
}

var file_dominus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dominus_proto_goTypes = []any{
	(*RequestMessage)(nil),  // 0: dominus.RequestMessage
	(*ResponseMessage)(nil), // 1: dominus.ResponseMessage
	(*Response)(nil),        // 2: dominus.Response
}
var file_dominus_proto_depIdxs = []int32{
	0, // 0: dominus.Grpc.Simple:input_type -> dominus.RequestMessage
	0, // 1: dominus.Grpc.ClientStream:input_type -> dominus.RequestMessage
	0, // 2: dominus.Grpc.ServerStream:input_type -> dominus.RequestMessage
	0, // 3: dominus.Grpc.BidirectionalStream:input_type -> dominus.RequestMessage
	2, // 4: dominus.Grpc.Simple:output_type -> dominus.Response
	2, // 5: dominus.Grpc.ClientStream:output_type -> dominus.Response
	1, // 6: dominus.Grpc.ServerStream:output_type -> dominus.ResponseMessage
	1, // 7: dominus.Grpc.BidirectionalStream:output_type -> dominus.ResponseMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dominus_proto_init() }
func file_dominus_proto_init() {
	if File_dominus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dominus_proto_rawDesc), len(file_dominus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dominus_proto_goTypes,
		DependencyIndexes: file_dominus_proto_depIdxs,
		MessageInfos:      file_dominus_proto_msgTypes,
	}.Build()
	File_dominus_proto = out.File
	file_dominus_proto_goTypes = nil
	file_dominus_proto_depIdxs = nil
}
