// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dominus.proto

package dominus

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RequestMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RequestMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RequestMessageMultiError,
// or nil if none found.
func (m *RequestMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Payload

	if len(errors) > 0 {
		return RequestMessageMultiError(errors)
	}

	return nil
}

// RequestMessageMultiError is an error wrapping multiple validation errors
// returned by RequestMessage.ValidateAll() if the designated constraints
// aren't met.
type RequestMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestMessageMultiError) AllErrors() []error { return m }

// RequestMessageValidationError is the validation error returned by
// RequestMessage.Validate if the designated constraints aren't met.
type RequestMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestMessageValidationError) ErrorName() string { return "RequestMessageValidationError" }

// Error satisfies the builtin error interface
func (e RequestMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestMessageValidationError{}

// Validate checks the field values on ResponseMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResponseMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResponseMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResponseMessageMultiError, or nil if none found.
func (m *ResponseMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *ResponseMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Payload

	if len(errors) > 0 {
		return ResponseMessageMultiError(errors)
	}

	return nil
}

// ResponseMessageMultiError is an error wrapping multiple validation errors
// returned by ResponseMessage.ValidateAll() if the designated constraints
// aren't met.
type ResponseMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResponseMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResponseMessageMultiError) AllErrors() []error { return m }

// ResponseMessageValidationError is the validation error returned by
// ResponseMessage.Validate if the designated constraints aren't met.
type ResponseMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResponseMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResponseMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResponseMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResponseMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResponseMessageValidationError) ErrorName() string { return "ResponseMessageValidationError" }

// Error satisfies the builtin error interface
func (e ResponseMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResponseMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResponseMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResponseMessageValidationError{}

// Validate checks the field values on Response with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Response with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResponseMultiError, or nil
// if none found.
func (m *Response) ValidateAll() error {
	return m.validate(true)
}

func (m *Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	if len(errors) > 0 {
		return ResponseMultiError(errors)
	}

	return nil
}

// ResponseMultiError is an error wrapping multiple validation errors returned
// by Response.ValidateAll() if the designated constraints aren't met.
type ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResponseMultiError) AllErrors() []error { return m }

// ResponseValidationError is the validation error returned by
// Response.Validate if the designated constraints aren't met.
type ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResponseValidationError) ErrorName() string { return "ResponseValidationError" }

// Error satisfies the builtin error interface
func (e ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResponseValidationError{}
